### PR TITLE
Verify j2objc version; out-of-box experience

### LINKED ISSUE #514: Verify j2objc version; and provide out-of-box experience.
If you specify a j2objc_home AND (`j2objc -version` returns `j2objc $j2objcVersion`), pass.
Otherwise, fast fail, and provide an exact command you can copy and paste, for example:
```
No matching version of j2objc could be found.  You can initiate a default installation of j2objc
by running the following from a Terminal:

  mkdir -p ~/j2objcDist && pushd ~/j2objcDist
  curl -L https://github.com/google/j2objc/releases/download/${j2objcVersion}/j2objc-${j2objcVersion}.zip > j2objc-${j2objcVersion}.zip
  unzip j2objc-${j2objcVersion}.zip
  echo j2objc.home=~/j2objcDist/j2objc-${j2objcVersion} >> ${rootProject.projectDir.absolutePath}/local.properties

Then rerun your Gradle build.

For advanced configuration of j2objc, please see http://j2objc.org/
```

Default j2objcConfig.j2objcVersion to 0.9.8.2.1.

### PR DESCRIPTION
**Pull request by advayDev1**
For now we provide instructions to the user re: how to install j2objc.

Fixes #514

TESTED=unit tests; local tests with modified systemTests build files

### CODE REVIEW

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy [hunk 1]
```diff
@@ -15,7 +15,6 @@
  */
 
 package com.github.j2objccontrib.j2objcgradle
-
```
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: We have the blank line by convention. I personally prefer it but more importantly we should be consistent.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy [hunk 2]
```diff
@@ -25,7 +24,6 @@ import org.gradle.api.Project
 import org.gradle.api.Task
 import org.gradle.api.tasks.util.PatternSet
 import org.gradle.util.ConfigureUtil
-
```
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: We have the blank line by convention. I personally prefer it but more importantly we should be consistent.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy (hunk 1 above)
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: ugh sorry. IntelliJ keeps doing this on its pre-commit cleanup

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy (hunk 2 above)
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: done

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy [hunk 3]
```diff
@@ -682,7 +691,67 @@ class J2objcConfig {
...
+                // Arguments
+                args "-version"
+
+                setStandardOutput stdout
+                setErrorOutput stderr
+            })
+
+        } catch (Exception exception) {
+            // Likely too old to understand -version.
+            Utils.throwJ2objcConfigFailure(project, "J2ObjC binary at $j2objcHome too old, v$j2objcVersion required.")
```
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: It's better to output stdout and stderr, just in case there's something like a permissions issue causing the problem. Then put the expected explanation at the bottom, so people will see that first. Look at how TestTask nests the errors:

https://github.com/j2objc-contrib/j2objc-gradle/blob/9758f8cffceb86b55c52f450408f517f1b77b6d7/src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/TestTask.groovy#L168

Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: done

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy [hunk 4]
```diff
@@ -682,7 +691,67 @@ class J2objcConfig {
...
 
+    protected void verifyJ2objcRequirements() {
+        if (skipJ2objcVerification) {
+            return
+        }
+
+        // Make sure we have *some* J2ObjC distribution identified.
+        // This will throw a proper out-of-box error if misconfigured.
+        String j2objcHome = Utils.j2objcHome(project)
+
```
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: Add check that j2objcVersion >= 0.9.8.2. If an earlier version is specified, then it should be rejected as the version string isn't supported. I think that's a reasonable request. To do the comparison, you could repurpose GradleVersion, not sure what would be a better approach.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy [hunk 5]
```diff
@@ -682,7 +691,67 @@ class J2objcConfig {
...
+            Utils.throwJ2objcConfigFailure(project, "J2ObjC binary does not exist at ${j2objcJar.absolutePath}.")
+        }
+
+        // Now check the version of the binary against the version required.
+        String j2objcExecutable = "$j2objcHome/j2objc"
+        List<String> windowsOnlyArgs = new ArrayList<String>()
+        if (Utils.isWindows()) {
+            j2objcExecutable = 'java'
+            windowsOnlyArgs.add('-jar')
+            windowsOnlyArgs.add("$j2objcHome/lib/j2objc.jar".toString())
```
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: Should be:

    windowsOnlyArgs.add(Utils.j2objcJar(project))

Repeat this for the same lines in CycleFinderTask and TranslateTask.

File: src/test/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfigTest.groovy [hunk 6]
```diff
@@ -15,7 +15,6 @@
  */
 
 package com.github.j2objccontrib.j2objcgradle
-
```
Comment (brunobowden) [inline src/test/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfigTest.groovy]: We have the blank line by convention. I personally prefer it but more importantly we should be consistent.

File: src/test/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfigTest.groovy [hunk 7]
```diff
@@ -24,12 +23,12 @@ import org.gradle.api.InvalidUserDataException
 import org.gradle.api.Project
 import org.gradle.testfixtures.ProjectBuilder
 import org.gradle.util.ConfigureUtil
+import org.hamcrest.core.StringContains
 import org.junit.Before
 import org.junit.Rule
 import org.junit.Test
 import org.junit.rules.ExpectedException
 import org.testng.Assert
-
```
Comment (brunobowden) [inline src/test/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfigTest.groovy]: We have the blank line by convention. I personally prefer it but more importantly we should be consistent.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy (hunk 5 above)
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: done

File: src/test/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfigTest.groovy (hunk 6 above)
Comment (advayDev1) [inline src/test/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfigTest.groovy]: done

File: src/test/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfigTest.groovy (hunk 7 above)
Comment (advayDev1) [inline src/test/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfigTest.groovy]: done

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy (hunk 4 above)
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: done

Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]:
```
A problem occurred evaluating root project 'simple1'.
> >>>>>>>>>>>>>>>> J2ObjC Tool Configuration Failure <<<<<<<<<<<<<<<<
  Must use at least J2ObjC version 0.9.8.2.1; you requested 0.9.8.2.
  
  If you do not have a J2ObjC v0.9.8.2.1 distribution,
  you can initiate a default installation of J2ObjC
  by running the following from a Terminal:
  
    J2OBJC_ROOT=~/j2objcDist
    mkdir -p $J2OBJC_ROOT; pushd $J2OBJC_ROOT
    curl -L https://github.com/google/j2objc/releases/download/0.9.8.2.1/j2objc-0.9.8.2.1.zip > j2objc-0.9.8.2.1.zip
    unzip j2objc-0.9.8.2.1.zip; popd
    sed -i '' '/j2objc.home/d' /Users/dev1/gitHubPublicRepos/j2objc-gradle/systemTests/simple1/local.properties
    echo j2objc.home=$J2OBJC_ROOT/j2objc-0.9.8.2.1 >> /Users/dev1/gitHubPublicRepos/j2objc-gradle/systemTests/simple1/local.properties
  
  Then rerun your Gradle build.
  
  For advanced configuration of j2objc, please see http://j2objc.org/
  If J2ObjC v0.9.8.2.1 is already installed, set J2ObjC Home either:
  1) in a 'local.properties' file in the project root directory as:
     j2objc.home=/LOCAL_J2OBJC_PATH
  2) as the J2OBJC_HOME system environment variable
  
  If both are configured the value in the properties file will be used.
```

**Comment by advayDev1** [comment]
ptal @brunobowden

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy [hunk 8]
```diff
@@ -682,7 +693,107 @@ class J2objcConfig {
         finalConfigured = true
     }
 
+    public static final String MIN_SUPPORTED_J2OBJC_VERSION = '0.9.8.2.1'
+
+    @VisibleForTesting
+    protected static List<Integer> parseVersionComponents(String ver) {
```
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: I think should go in to Utils. Along with possibly the validateNumericVersion method.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy [hunk 9]
```diff
@@ -682,7 +693,107 @@ class J2objcConfig {
...
+        // Each existing component was equal.  If the requested version is at least as long, we're good.
+        return versionComponents.size() >= minVersionComponents.size()
+    }
+
+    protected void verifyJ2objcRequirements() {
+        if (skipJ2objcVerification) {
+            return
+        }
+
+        if (!isAtLeastVersion(j2objcVersion, MIN_SUPPORTED_J2OBJC_VERSION)) {
```
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: It should be an exact match for a repeatable build, not a minimum.

Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: Scrub that, you're doing the exact match check below.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/Utils.groovy [hunk 10]
```diff
@@ -245,27 +246,60 @@ class Utils {
...
+                         // Unzip the distribution (only).
+                         "  unzip j2objc-${ver}.zip; popd\n" +
+                         // Eliminate any existing value in local.properties.
+                         "  sed -i '' '/j2objc.home/d' $propFile\n" +
+                         // Add a new value for j2objc.home to local.properties.
+                         "  echo j2objc.home=\$J2OBJC_ROOT/j2objc-${ver} >> $propFile\n" +
+                         "\n" +
+                         "Then rerun your Gradle build.\n" +
+                         "\n" +
+                         "For advanced configuration of j2objc, please see http://j2objc.org/\n" +
```
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/Utils.groovy]: j2objc => J2ObjC in text

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/Utils.groovy [hunk 11]
```diff
@@ -245,27 +246,60 @@ class Utils {
...
+                         "If J2ObjC v${ver} is already installed, set J2ObjC Home either:\n" +
+                         "1) in a 'local.properties' file in the project root directory as:\n" +
+                         "   j2objc.home=/LOCAL_J2OBJC_PATH\n" +
+                         "2) as the J2OBJC_HOME system environment variable\n" +
+                         "\n" +
+                         "If both are configured the value in the properties file will be used."
+        throw new InvalidUserDataException(message)
+    }
+
     static String j2objcHasOsxDistribution(Project proj) {
```
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/Utils.groovy]: Why is the return type a String when the `exists()` method returns a boolean? I'm surprised at this given that @CompileStatic is applied to the class. Might as well fix that while you're here.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/Utils.groovy (hunk 10 above)
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/Utils.groovy]: done

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/Utils.groovy (hunk 11 above)
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/Utils.groovy]: lol done

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy [hunk 12]
```diff
@@ -682,7 +693,107 @@ class J2objcConfig {
...
+    @VisibleForTesting
+    protected static List<Integer> parseVersionComponents(String ver) {
+        return ver.tokenize('.').collect({String versionComponent ->
+            try {
+                return Integer.parseInt(versionComponent)
+            } catch (NumberFormatException nfe) {
+                // Keep it simple.  If the version provided doesn't meet a simple N.N.N format,
+                // assume the user knows what they are doing and keep going.  The maximum integer
+                // provides this behavior.
+                return Integer.MAX_VALUE
```
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: What about extracting all the digits and then just doing a compare by that?

That'll fix the following example:
```
! assert J2objcConfig.isAtLeastVersion("0.9.8.2.1-SNAPSHOT", "0.9.8.2.2")
```

**Comment by brunobowden** [comment]
LGTM - just have a look at the comments and address the ones that make sense to you.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy (hunk 12 above)
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: I'd rather not - it seems like overkill.  If you're getting snapshots and such you know what you're doing.

Once j2objc hits 1.0, hopefully we just set the min to 1.0 and don't worry about it - it is a stop gap until then.

**Comment by advayDev1** [comment]
Thanks!  Did all except handling non-integer versions.  When Travis passes I'll merge.
