### PR TITLE
Minimum OS versions, fixed iOS & OS X builds

### LINKED ISSUE #520: Fix iOS and OS X builds
Turns that a whole host of changes are needed to get the build working simultaneously on iOS and OS X. I won't enumerate the changes here, instead see the upcoming PR to fix all of it.

### PR DESCRIPTION
**Pull request by brunobowden**
- Minimum OS versions for iOS, OS X and watchOS
- xcodeTargets => xcodeTargetsIos, xcodeTargetsOsx & xcodeTargetsWatchos
- Extensive refactoring of Podfile updating logic
- Extensive unit tests for all the forgoing changes
- Fixes #520

TODO: get watchOS build working

### CODE REVIEW

**Comment by brunobowden** [comment]
@advayDev1 - This was the main blocker I had for the 0.5 release. I will be following along with a more extensive system test for it.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy [hunk 1]
```diff
@@ -638,7 +640,8 @@ class J2objcConfig {
      * <p/>
      * See https://developer.apple.com/library/ios/documentation/DeveloperTools/Conceptual/cross_development/Configuring/configuring.html#//apple_ref/doc/uid/10000163i-CH1-SW2
      */
-    String minWatchosVersion = '1.0'
+    // Matches the oldest version supported in Xcode 7
+    String minVersionWatchos = '1.0'
```
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: i'm intrigued as to how this is working right now.  the watch version is not used in the native build, only in the podspec.   does native build not need to know about watch os?

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy [hunk 2]
```diff
@@ -649,28 +652,54 @@ class J2objcConfig {
...
-     * If this is never called, it will default to linking all targets
-     * to the generated shared library.
+     * @param xcodeTargetsIos links targets to generated library.
+     */
+    void xcodeTargetsIos(String... xcodeTargetsIos) {
+        appendArgs(this.xcodeTargetsIos, 'xcodeTargetsIos', xcodeTargetsIos)
+    }
+
+    /**
+     * Xcode ios app and test targets that should be linked to the generated library.
```
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: ios -> OS X

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy [hunk 3]
```diff
@@ -649,28 +652,54 @@ class J2objcConfig {
...
+     * @param xcodeTargetsIos links targets to generated library.
      */
-    void xcodeTargets(String... xcodeTargets) {
-        appendArgs(this.xcodeTargets, 'xcodeTargets', xcodeTargets)
+    void xcodeTargetsOsx(String... xcodeTargetsOsx) {
+        appendArgs(this.xcodeTargetsOsx, 'xcodeTargetsOsx', xcodeTargetsOsx)
     }
 
+    /**
+     * Xcode ios app and test targets that should be linked to the generated library.
```
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: iOS -> WatchOS

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy [hunk 4]
```diff
@@ -649,28 +652,54 @@ class J2objcConfig {
...
+     *
+     * This will automatically add linkage for any target in the specified list
+     * to the generated shared library. This should include associated Test targets.
+     */
+    List<String> xcodeTargetsWatchos = new ArrayList<>()
+    /**
+     * Add targets within Xcode to link to the generated shared library.
+     *
+     * @param xcodeTargetsIos links targets to generated library.
```
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: fix param name

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy [hunk 5]
```diff
@@ -649,28 +652,54 @@ class J2objcConfig {
...
+     *
+     * This will automatically add linkage for any target in the specified list
+     * to the generated shared library. This should include associated Test targets.
+     */
+    List<String> xcodeTargetsOsx = new ArrayList<>()
+    /**
+     * Add targets within Xcode to link to the generated shared library.
      *
-     * @param xcodeTargets links targets to generated library.
+     * @param xcodeTargetsIos links targets to generated library.
```
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: param name

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/PodspecTask.groovy [hunk 6]
```diff
@@ -68,11 +68,11 @@ class PodspecTask extends DefaultTask {
     String getPodNameRelease() { "j2objc-${project.name}-release" }
 
     @Input
-    String getMinIosVersion() { return J2objcConfig.from(project).getMinIosVersion() }
+    String getMinIosVersion() { return J2objcConfig.from(project).getMinVersionIos() }
```
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/PodspecTask.groovy]: since you renamed the variable also rename these accessors

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy (hunk 1 above)
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: As the title notes, this gets iOS and OS X working... I haven't got watchOS working yet. This is a necessary step, so I wanted to include it. I can comment it out for now if you want.

Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: nah, keep it in.  please do note in the commit that watchOS does not work though.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/XcodeTask.groovy [hunk 7]
```diff
@@ -362,71 +451,41 @@ class XcodeTask extends DefaultTask {
...
-                        }
-                        podMethodProcessed = true
-                    }
-                }
-            }
-
-            if (!skipWritingLine) {
-                newPodfileLines.add(line)
-            }
+    static List<String> updatePodfileTargets(
```
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/XcodeTask.groovy]: this is getting to be a lot of parameters.

perhaps a data structure would be useful here?  Like PlatformConfig that has a list of targets and a min version?

**Comment by advayDev1** [comment]
lgtm with comments

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy (hunk 2 above)
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: done

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy (hunk 3 above)
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: done

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy (hunk 4 above)
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: done

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy (hunk 5 above)
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcConfig.groovy]: done

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/PodspecTask.groovy (hunk 6 above)
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/PodspecTask.groovy]: done

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/XcodeTask.groovy (hunk 7 above)
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/XcodeTask.groovy]: I've grouped all the xcodeTargets... and minVersion... in to a `XcodeTargetDetails` structure. I agree that it's much better with this change.
