### PR TITLE
iOS and OS X library dependencies

### LINKED ISSUE #488: XcodeTask must distinguish ios vs osx for Xcode 7
@brunobowden - can the pod config specify:
- different j2objc library directories for ios vs. osx (j2objcDist/lib and j2objcDist/lib/macosx respectively)
- different project library directories for ios vs. osx (project/build/j2objcOutputs/lib/ios{Debug|Release} vs project/build/j2objcOutputs/lib/x86_64{Debug|Release})
- one additional framework for osx (ExceptionHandling)?

### PR DESCRIPTION
**Pull request by brunobowden**
- separate iOS and OS X libraries for j2objc
- separate iOS and OS X libraries built libraries
- min deployment target (default): iOS (8.3), OS X (10.8) & watchOS (2.0)
- Standardize buildType on uppercase ‘Debug’ and ‘Release’
- Link to ExceptionHandling library only on OS X

Fixes #488

### CODE REVIEW

**Comment by brunobowden** [comment]
@advayDev1 - do you know what line is needed for the podspec? I believe it's vendored_libraries. Are you using an OS X build at the moment? If you have an example, it would be helpful to submit it.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/PodspecTask.groovy [hunk 1]
```diff
@@ -89,15 +86,17 @@ class PodspecTask extends DefaultTask {
 
         // podspec creation
         // TODO: allow custom list of libraries
-        String libDirDebug = new File(getDestLibDirFile(), '/iosDebug').absolutePath
-        String libDirRelease = new File(getDestLibDirFile(), '/iosRelease').absolutePath
+        String libDirIosDebug = new File(getDestLibDirFile(), '/iosDebug').absolutePath
+        String libDirIosRelease = new File(getDestLibDirFile(), '/iosRelease').absolutePath
+        String libDirOsxDebug = new File(getDestLibDirFile(), '/x86_64Debug').absolutePath
+        String libDirOsxRelease = new File(getDestLibDirFile(), '/x86_64Release').absolutePath
```
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/PodspecTask.groovy]: i'm having second thoughts about the ordering here.
Does absolutePath function before the directory is created?  I thought the FS actually resolves the path?

Until the AssembleLibrariesTask has run, j2objcOutputs/lib/BLAH is never created.  Does this work for you after a ./gradlew clean then ./gradlew build?

Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/PodspecTask.groovy]: The ordering is fine. The absolutePath is resolved internally without referencing the FS. I can run `j2objcPodspec` and it happily refers to a non-existent directory. Then after running the full build, it now refers to a directory that exists. Indeed, the clean and then build is enforced by the `run-test.sh` script.

**Comment by brunobowden** [comment]
@advayDev1 - I've reworked this to add the deployment targets for iOS, OS X and watchOS. I'm going to try and setup a "allPlatforms" test that builds on all the platforms. What is the j2objcConfig to add the bitcode build? Given that this is only partially working, please review as is and then I'll work on a separate PR for the platform builds.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/Utils.groovy [hunk 2]
```diff
@@ -60,6 +60,14 @@ class Utils {
         }
     }
 
+    static void validateVersion(String version, String type) {
+        // Requires at least a major and minor version number
+        Matcher versionMatcher = (version =~ /^[0-9]*(\.[0-9]+)+$/)
```
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/Utils.groovy]: this prohibits -rc1, .beta, etc.
we know that won't happen?

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/PodspecTask.groovy [hunk 3]
```diff
@@ -89,15 +88,24 @@ class PodspecTask extends DefaultTask {
...
+
+        J2objcConfig j2objcConfig = J2objcConfig.from(project)
 
         String podspecContentsDebug =
-                genPodspec(getPodNameDebug(), libDirDebug, libName, getJ2objcHome(),
-                        headerIncludePath, resourceIncludePath)
+                genPodspec(getPodNameDebug(), headerIncludePath, resourceIncludePath,
```
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/PodspecTask.groovy]: a comment above this statement that watchos and ios share their lib directories would be helpful given the partial aliasing of parameter names

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/NativeCompilation.groovy [hunk 4]
```diff
@@ -307,12 +307,12 @@ class NativeCompilation {
             // https://docs.gradle.org/current/userguide/nativeBinaries.html#N161B3
             task('j2objcBuildObjcDebug').configure {
                 dependsOn binaries.withType(NativeLibraryBinary).matching { NativeLibraryBinary lib ->
-                    lib.buildable && lib.buildType.name == 'debug'
```
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/NativeCompilation.groovy]: Must revert this change.  Internally the build type is lower case.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/NativeCompilation.groovy [hunk 5]
```diff
@@ -307,12 +307,12 @@ class NativeCompilation {
...
+                    lib.buildable && lib.buildType.name == 'Debug'
                 }
             }
             task('j2objcBuildObjcRelease').configure {
                 dependsOn binaries.withType(NativeLibraryBinary).matching { NativeLibraryBinary lib ->
-                    lib.buildable && lib.buildType.name == 'release'
```
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/NativeCompilation.groovy]: Must revert this change.  Internally the build type is lower case.

**Comment by advayDev1** [comment]
Build is failing due to the change re: case - see comments above.  LGTM after that.

Unfortunately I don't use bitcode nor do I know much about it.
If you need an extra compiler arg: j2objcConfig.extraObjcCompilerArgs
linker: j2objcConfig.extraLinkerArgs

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/Utils.groovy (hunk 2 above)
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/Utils.groovy]: I've renamed it to validateNumericVersion and shifted it from Utils to PodspecTask, chaning it from an exception to a warning. I've never seen an Apple OS with a non numeric identifier but can't definitively confirm that there won't ever be one.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/NativeCompilation.groovy (hunk 4 above)
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/NativeCompilation.groovy]: Reverted to 'debug'

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/NativeCompilation.groovy (hunk 5 above)
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/NativeCompilation.groovy]: Reverted to 'release'
