### PR TITLE
Correctly scope input and ouputs for AssembleLibrariesTask

### LINKED ISSUE #505: j2objcAssembleDebug fails UP-TO-DATE due to shared directory for debug / release build
For simple1 test, running `j2objcBuild` twice in succession shouldn't repeat running the same task twice. In this case, `j2objcAssembleDebug` fails the UP-TO-DATE on the 2nd build. It should pass. This occurs due to the debug and release builds sharing the same directory for the static libraries.

These folders need to be split, so that the debug and release libraries are written to separate directories.

```
:j2objcAssembleDebug (Thread[Daemon worker Thread 9,5,main]) started.
:j2objcAssembleDebug
Executing task ':j2objcAssembleDebug' (up-to-date check took 0.005 secs) due to:
  Input file /Users/brunobowden/dev/j2objc-gradle/systemTests/simple1/build/binaries/simple1-j2objcStaticLibrary/ios_arm64Release/libsimple1-j2objc.a has been added.
  Input file /Users/brunobowden/dev/j2objc-gradle/systemTests/simple1/build/binaries/simple1-j2objcStaticLibrary/ios_armv7Release/libsimple1-j2objc.a has been added.
  Input file /Users/brunobowden/dev/j2objc-gradle/systemTests/simple1/build/binaries/simple1-j2objcStaticLibrary/ios_x86_64Release/libsimple1-j2objc.a has been added.
```

### PR DESCRIPTION
**Pull request by advayDev1**
Fixes #505

TESTED=
- simple1 system test built twice idempotently
- then modified only debug files and it only rebuilt debug

### CODE REVIEW

**Comment by advayDev1** [comment]
ptal @brunobowden

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/AssembleLibrariesTask.groovy [hunk 1]
```diff
@@ -32,20 +33,42 @@ import org.gradle.api.tasks.TaskAction
...
     File srcLibDir
-
-    @InputDirectory
     File srcPackedLibDir
 
+    // Only treat as inputs the files of relevant buildType.
+    @InputFiles
+    FileTree getSrcLibs() {
+        return project.fileTree(dir: srcLibDir, include: "*$buildType/*.a") +
+               project.fileTree(dir: srcPackedLibDir, include: "*$buildType/*.a")
```
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/AssembleLibrariesTask.groovy]: Should "*$buildType/*.a" be extracted since it's used in 3 places?

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/AssembleLibrariesTask.groovy [hunk 2]
```diff
@@ -32,20 +33,42 @@ import org.gradle.api.tasks.TaskAction
...
     File getDestLibDirFile() { return J2objcConfig.from(project).getDestLibDirFile() }
 
+    // Only treat as outputs the directories of relevant buildType.
+    @SuppressWarnings('unused')
+    @OutputDirectories
+    List<File> getDestLibSubdirs() {
+        List<File> inputDirs = []
+        FileFilter filter = new FileFilter() {
+            @Override boolean accept(File pathname) {
+                return pathname.isDirectory() && pathname.name.endsWith(buildType)
```
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/AssembleLibrariesTask.groovy]: Why this `isDirectory()` test? Add comment on this.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/AssembleLibrariesTask.groovy [hunk 3]
```diff
@@ -32,20 +33,42 @@ import org.gradle.api.tasks.TaskAction
...
+            }
+        }
+        File[] filtered = srcLibDir.listFiles(filter)
+        if (filtered != null) {
```
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/AssembleLibrariesTask.groovy]: When is this null? I'm not sure if that should ever happen. It might be that the Debug libraries aren't built but then shouldn't the assembleLibrariesDebug not be run either?

**Comment by brunobowden** [comment]
LGTM with comments

In some ways, it would be easier splitting this in to a debug and release directory but I can see why that doesn't work as well.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/AssembleLibrariesTask.groovy (hunk 1 above)
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/AssembleLibrariesTask.groovy]: dont

Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/AssembleLibrariesTask.groovy]: er "done"

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/AssembleLibrariesTask.groovy (hunk 2 above)
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/AssembleLibrariesTask.groovy]: other stuff can be in there.  a .DSStore for example

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/AssembleLibrariesTask.groovy (hunk 3 above)
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/AssembleLibrariesTask.groovy]: It can legitimately be null when the parent directory doesn't exist. If the superior tasks are disabled, it would be correct for this task not to pack nothing.

When testing we don't actually create all these directories either.

Comment added.

**Comment by advayDev1** [comment]
The directory naming structure follows the default one used by Gradle: namely [architecture][BuildType].  I wish it used hierarchy, but it doesn't.  Following this structure allows other Gradle native project to easily  link to the output of our plugin.

**Comment by brunobowden** [comment]
Fair point on dependant projects. Agreed on keeping the structure as is.
