### PR TITLE
BUGFIX: Fix incremental translations

### LINKED ISSUE #159: When local sources are unchanged, but dependencies change, translate task fails
Currently if one of your class libs or other dependencies of j2objcTranslate changes BUT none of the main source files does, it will try to re-translate 0 source files.  The correct thing to do when a non-source file changes is to retranslate everything.

### PR DESCRIPTION
**Pull request by advayDev1**
Prereqs: #157 #158

Currently if one of your class libs or other dependencies of j2objcTranslate changes BUT none of the main source files does, it will try to re-translate 0 source files. The correct thing to do when a non-source file changes is to retranslate everything.

Fixes #159

### CODE REVIEW

**Comment by brunobowden** [comment]
@advayDev1 - I'll look at this later on today

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/J2objcTestTask.groovy [hunk 1]
```diff
@@ -138,7 +138,7 @@ class J2objcTestTask extends DefaultTask {
                 "    testMinExpectedTests ${testCount}\n" +
                 "}\n"
         if (getTestMinExpectedTests() == 0) {
-            logger.warning "Min Test check disabled due to: 'testMinExpectedTests 0'"
+            logger.warn "Min Test check disabled due to: 'testMinExpectedTests 0'"
```
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/J2objcTestTask.groovy]: Was this silently failing?

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/J2objcTranslateTask.groovy [hunk 2]
```diff
@@ -155,34 +148,43 @@ class J2objcTranslateTask extends DefaultTask {
...
+                // make an incremental change which refers to a not yet translated class from a
+                // source lib. In this case due to not using --build-closure the dependent source
+                // will not be translated, this can be fixed with a clean and fresh build.
+                // Due to this issue, incremental builds with --build-closure are enabled ONLY
+                // if the user requests it with the UNSAFE_incrementalBuildClosure flag.
+                if (translatedFiles > 0 && project.j2objcConfig.UNSAFE_incrementalBuildClosure) {
+                    translateFlags = translateFlags.toString().replaceFirst("--build-closure", "").trim()
+                }
+            } else {
+                // A non-source file changed, we can't do an incremental build.
```
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/J2objcTranslateTask.groovy]: Reword as:

    // A change outside of the srcFiles directory has occurred, so an incremental build isn't possible

**Comment by brunobowden** [comment]
I'll look more closely at this after #157 and #158 are merged

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcNativeCompilation.groovy [hunk 3]
```diff
@@ -1,17 +1,23 @@
...
 import org.gradle.nativeplatform.NativeLibrarySpec
 import org.gradle.nativeplatform.toolchain.Clang
-
 /**
  *
  */
 class J2objcNativeCompilation {
-    def apply(Project project, File srcGenDir) {
+
+    final Project project
```
Comment (confile) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcNativeCompilation.groovy]: private final Project project

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcNativeCompilation.groovy [hunk 4]
```diff
@@ -245,6 +269,12 @@ class J2objcNativeCompilation {
             }
         }
     }
+
+    List<Project> beforeProjects = []
```
Comment (confile) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcNativeCompilation.groovy]: private List<Project> beforeProjects = []

**Comment by confile** [comment]
@advayDev1 As a side note it is very hard to understand why the j2objc gradle plugin adds a lot of new tasks for different platforms. When running the Xcode task all platforms where compiled. I suppose that incremental compilation will do the incremental compile for each platform. This tasks a lot of time. You can be sure that not all platforms are used by the plugin user. So it might be better to have a flag in the plugin's extensions to specify the used platforms. A comment should make clear where to find them in Xcode settings.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/J2objcTestTask.groovy (hunk 1 above)
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/J2objcTestTask.groovy]: yeah, beauty of Groovy ;)  (doesn't fail until you run this line).

We can use static typing annotations for certain classes to catch such errors on compile.

**Comment by advayDev1** [comment]
@confile - good point about platforms, but remember this PR is about incremental *translation* which is entirely separate from incremental *compilation*.  I am adding functionality to PR #158 to support optional user selection of architectures, it is easy now (unfortunately it used to be impossible until the fix of PR #157).

**Comment by confile** [comment]
@advayDev1 Ok, but still you should document this. I create an issue for that.

**Comment by confile** [comment]
https://github.com/j2objc-contrib/j2objc-gradle/issues/177

**Comment by advayDev1** [comment]
thank you!  will reference that issue.

**Comment by advayDev1** [comment]
@brunobowden , PTAL, comment resolved.
@confile , those diffs are not in this PR.?

**Comment by confile** [comment]
@advayDev1 Which diffs?

**Comment by advayDev1** [comment]
@confile - the comments you made are for lines not in this PR.  I think they are for a different PR, #158.  if that is true, I will make the fixes over there.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcNativeCompilation.groovy (hunk 4 above)
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcNativeCompilation.groovy]: fixed in #158

**Comment by confile** [comment]
@advayDev1  ok

**Comment by advayDev1** [comment]
ping @brunobowden  - should be straightforward now.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/J2objcTranslateTask.groovy [hunk 5]
```diff
@@ -141,34 +148,43 @@ class J2objcTranslateTask extends DefaultTask {
...
-            if (srcGenDir.exists()) {
-                FileCollection destFiles = project.files(project.fileTree(
-                        dir: srcGenDir, includes: ["**/*.h", "**/*.m"]))
-
-                // remove translated .h and .m files which has no corresponding .java files anymore
-                destFiles.each { File file ->
-                    def nameWithoutExt = file.name.toString().replaceFirst("\\..*", "")
-                    if (removedFileNames.contains(nameWithoutExt)) {
-                        file.delete()
+            if (!nonSourceFileChanged) {
```
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/J2objcTranslateTask.groovy]: Add comment to explain logic inside `if`:

    // changes isolated to srcFiles only

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/J2objcTranslateTask.groovy [hunk 6]
```diff
@@ -141,34 +148,43 @@ class J2objcTranslateTask extends DefaultTask {
...
+                def translatedFiles = 0
+                if (srcGenDir.exists()) {
+                    FileCollection destFiles = project.files(project.fileTree(
+                            dir: srcGenDir, includes: ["**/*.h", "**/*.m"]))
+
+                    // remove translated .h and .m files which has no corresponding .java files anymore
+                    destFiles.each { File file ->
+                        def nameWithoutExt = file.name.toString().replaceFirst("\\..*", "")
+                        if (removedFileNames.contains(nameWithoutExt)) {
```
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/J2objcTranslateTask.groovy]: Add comment explaining why the `if (removedFileNames.contains(nameWithoutExt))` is needed. Is there not just a one-to-one correspondence between srcFiles and srcGenDir files?

Also, do we need to add a TODO for the case of name collisions since we're not comparing the full path?

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/J2objcTranslateTask.groovy [hunk 7]
```diff
@@ -141,34 +148,43 @@ class J2objcTranslateTask extends DefaultTask {
...
+                // make an incremental change which refers to a not yet translated class from a
+                // source lib. In this case due to not using --build-closure the dependent source
+                // will not be translated, this can be fixed with a clean and fresh build.
+                // Due to this issue, incremental builds with --build-closure are enabled ONLY
+                // if the user requests it with the UNSAFE_incrementalBuildClosure flag.
+                if (translatedFiles > 0 && project.j2objcConfig.UNSAFE_incrementalBuildClosure) {
+                    translateFlags = translateFlags.toString().replaceFirst("--build-closure", "").trim()
+                }
+            } else {
+                // A change outside of the source set directories has occurred, so an incremental build isn't possible.
```
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/J2objcTranslateTask.groovy]: Add comment explaining common situations which causes this

**Comment by brunobowden** [comment]
Looks good - please take a look at the final comments then feel free to merge

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/J2objcTranslateTask.groovy (hunk 5 above)
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/J2objcTranslateTask.groovy]: done

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/J2objcTranslateTask.groovy (hunk 6 above)
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/J2objcTranslateTask.groovy]: done

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/J2objcTranslateTask.groovy (hunk 7 above)
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/J2objcTranslateTask.groovy]: done
