### PR TITLE
Warn when using -fobjc-arc without -use-arc. fixes #195

### LINKED ISSUE #195: error: 'autorelease' is unavailable: not available in automatic reference counting mode
I tried to compile to following class: 

```
package com.example;

import java.util.Date;

public class SharedClass {
  public static Date getDate() {
    return new Date();
  }
}
```

and got this error: 

```
:compileIos_arm64DebugShared-j2objcStaticLibraryShared-j2objcObjc
/Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/shared/build/j2objcSrcGen/SharedClass.m:45:35: error: 'autorelease' is unavailable: not available in automatic reference counting mode
  return [new_JavaUtilDate_init() autorelease];
                                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/objc/NSObject.h:38:1: note: 'autorelease' has been explicitly marked unavailable here
- (instancetype)autorelease OBJC_ARC_UNAVAILABLE;
^
/Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/shared/build/j2objcSrcGen/SharedClass.m:45:35: error: ARC forbids explicit message send of 'autorelease'
  return [new_JavaUtilDate_init() autorelease];
          ~~~~~~~~~~~~~~~~~~~~~~~ ^
2 errors generated.

:compileIos_arm64DebugShared-j2objcStaticLibraryShared-j2objcObjc FAILED
```

Config: 

```
j2objcConfig {
    xcodeProjectDir "${projectDir}/../ios"   // Xcode workspace directory
    xcodeTarget "ios"                        // Xcode application target name
    // More: https://github.com/j2objc-contrib/j2objc-gradle/blob/master/src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPluginExtension.groovy#L25

    translateFlags "--no-package-directories"
	  extraObjcCompilerArgs += '-fobjc-arc'
	
	  finalConfigure()
}
```

### PR DESCRIPTION
**Pull request by confile**

### CODE REVIEW

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy [hunk 1]
```diff
@@ -71,6 +71,11 @@ class J2objcPlugin implements Plugin<Project> {
                                 "-fobjc-arc enables Automatic Reference Counting functionality in the compiler:\n" +
                                 "https://developer.apple.com/library/mac/releasenotes/ObjectiveC/RN-TransitioningToARC/Introduction/Introduction.html#//apple_ref/doc/uid/TP40011226-CH1-SW15"
                 }
+				if (('-fobjc-arc' in evaluatedProject.j2objcConfig.extraObjcCompilerArgs) &&
+                    !evaluatedProject.j2objcConfig.translateFlags.contains('-use-arc')) {
+                    logger.warn "${evaluatedProject.name}: When using Objective C compiler flag -fobjc-arc you have " +
+                                "to use the '-use-arc' translate flag"
```
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy]: please make this message more similar to the one above, where you provide an actual configuration excerpt, and you also give a link to the j2objc website that discusses -use-arc

**Comment by confile** [comment]
@advayDev1  done

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy [hunk 2]
```diff
@@ -63,7 +63,7 @@ class J2objcPlugin implements Plugin<Project> {
                 if (!('-fobjc-arc' in evaluatedProject.j2objcConfig.extraObjcCompilerArgs) &&
                     evaluatedProject.j2objcConfig.translateFlags.contains('-use-arc')) {
                     logger.warn "${evaluatedProject.name}: When translating with -use-arc, it is recommended " +
-                                "to use the '-fobjc-arc' Objective C compiler flag, ex:\n"
+                                "to use the '-fobjc-arc' Objective C compiler flag, ex:\n" +
```
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy]: thanks for the fix!

Comment (confile) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy]: Your welcome!

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy [hunk 3]
```diff
@@ -71,6 +71,18 @@ class J2objcPlugin implements Plugin<Project> {
...
+		
+		if (('-fobjc-arc' in evaluatedProject.j2objcConfig.extraObjcCompilerArgs) &&
+                    !evaluatedProject.j2objcConfig.translateFlags.contains('-use-arc')) {
+                    logger.warn "${evaluatedProject.name}: When using Objective C compiler flag -fobjc-arc you have " +
+                                "to use the '-use-arc' translate flag, ex:\n" +
+                                "j2objcConfig {\n" +
+                                "    // other settings\n" +
+                                "    translateFlags '-use-arc'\n" +
+                                "}\n" +
+                                "-fobjc-arc enables Automatic Reference Counting functionality in the compiler:\n" +
```
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy]: no, this is the reference for -fobjc-arc.  you need the reference on j2objc's website about -use-arc

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy [hunk 4]
```diff
@@ -71,6 +71,18 @@ class J2objcPlugin implements Plugin<Project> {
                                 "-fobjc-arc enables Automatic Reference Counting functionality in the compiler:\n" +
                                 "https://developer.apple.com/library/mac/releasenotes/ObjectiveC/RN-TransitioningToARC/Introduction/Introduction.html#//apple_ref/doc/uid/TP40011226-CH1-SW15"
                 }
+		
+		if (('-fobjc-arc' in evaluatedProject.j2objcConfig.extraObjcCompilerArgs) &&
```
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy]: Indentation is misaligned by one space

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy (hunk 3 above)
Comment (confile) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy]: done

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy (hunk 4 above)
Comment (confile) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy]: done

**Comment by confile** [comment]
done

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy (hunk 3 above)
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy]: this line in the comment would be better as "-use-arc translates Java into Objective C using Automatic Reference Counting:\n"

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy [hunk 5]
```diff
@@ -71,6 +71,18 @@ class J2objcPlugin implements Plugin<Project> {
                                 "-fobjc-arc enables Automatic Reference Counting functionality in the compiler:\n" +
                                 "https://developer.apple.com/library/mac/releasenotes/ObjectiveC/RN-TransitioningToARC/Introduction/Introduction.html#//apple_ref/doc/uid/TP40011226-CH1-SW15"
                 }
+		
+		            if (('-fobjc-arc' in evaluatedProject.j2objcConfig.extraObjcCompilerArgs) &&
```
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy]: this line (possible others) is using tabs (\t).
you need to use only 4-spaces, never tabs to indent in this codebase.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy (hunk 3 above)
Comment (confile) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy]: done

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy (hunk 5 above)
Comment (confile) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy]: @advayDev1 Really you never use tabs why?

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy [hunk 6]
```diff
@@ -71,6 +71,18 @@ class J2objcPlugin implements Plugin<Project> {
...
+                    !evaluatedProject.j2objcConfig.translateFlags.contains('-use-arc')) {
+                    logger.warn "${evaluatedProject.name}: When using Objective C compiler flag -fobjc-arc you have " +
+                                "to use the '-use-arc' translate flag, ex:\n" +
+                                "j2objcConfig {\n" +
+                                "    // other settings\n" +
+                                "    translateFlags '-use-arc'\n" +
+                                "}\n" +
+                                "-fobjc-arc enables Automatic Reference Counting functionality in the compiler:\n" +
+                                "https://developer.apple.com/library/mac/releasenotes/ObjectiveC/RN-TransitioningToARC/Introduction/Introduction.html#//apple_ref/doc/uid/TP40011226-CH1-SW15"
+                }
```
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy]: There's a lot of repetition here, which isn't a good practice. I would combine them in to a single test:

```
Boolean arcTranslateArg = '-use-arc' in evaluatedProject.j2objcConfig.translateFlags
Boolean arcCompilerArg = '-fobjc-arc' in evaluatedProject.j2objcConfig.extraObjcCompilerArgs
if (arcTranslateArg && !arcCompilerArg || !arcTranslateArg && arcCompilerArg) {
    logger.warn "${evaluatedProject.name}: using ARC with J2ObjC, the project is missing one of the two flags required:\n" +
                "\n" +
                "j2objcConfig {\n" +
                "    // other settings\n" +
                "    translateFlags '-use-arc'\n" +
                "    extraObjcCompilerArgs = ['-fobjc-arc']\n" +
                "}\n" +
                "-fobjc-arc enables Automatic Reference Counting functionality in the compiler:\n" +
                "https://developer.apple.com/library/mac/releasenotes/ObjectiveC/RN-TransitioningToARC/Introduction/Introduction.html#//apple_ref/doc/uid/TP40011226-CH1-SW15"
}
```

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy (hunk 5 above)
Comment (confile) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy]: fixed

Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy]: the entire codebase uses 4-spaces.  no tabs should exist anywhere.

i don't actually care whether we used 4-spaces or tabs, but since the code already uses one style, it has to be followed in all other parts of the codebase.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy (hunk 6 above)
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy]: while i agree with the idea, i think the error message is unnecessarily confusing.
i'd keep the config block and references the same, but identify the actually missing flag in the first line of the message.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy (hunk 5 above)
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy]: btw, in #97 we proposed using the groovy style guide as our official style guide:
http://www.groovy-lang.org/style-guide.html

Unfortunately it is not comprehensive, so I'd suggest that whenever the Groovy style guide doesn't provide a conflict instruction, we use the Google Java style guide.  In this case for example, Groovy style guide does not dictate indentation, but the Google Java style guide does:
https://google-styleguide.googlecode.com/svn/trunk/javaguide.html#s2.3.1-whitespace-characters

cc @brunobowden  - i will add this to the bug

**Comment by confile** [comment]
done

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy (hunk 5 above)
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy]: Use lowercase boolean primitives not Boolean the object

**Comment by confile** [comment]
done

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy [hunk 7]
```diff
@@ -60,17 +60,19 @@ class J2objcPlugin implements Plugin<Project> {
...
-                                "to use the '-fobjc-arc' Objective C compiler flag, ex:\n"
-                                "j2objcConfig {\n" +
-                                "    // other settings\n" +
-                                "    extraObjcCompilerArgs += '-fobjc-arc'\n" +
-                                "}\n" +
-                                "-fobjc-arc enables Automatic Reference Counting functionality in the compiler:\n" +
-                                "https://developer.apple.com/library/mac/releasenotes/ObjectiveC/RN-TransitioningToARC/Introduction/Introduction.html#//apple_ref/doc/uid/TP40011226-CH1-SW15"
-                }
+                Boolean arcTranslateArg = '-use-arc' in evaluatedProject.j2objcConfig.translateFlags
+                Boolean arcCompilerArg = '-fobjc-arc' in evaluatedProject.j2objcConfig.extraObjcCompilerArgs
```
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy]: Should be lower `boolean`, my mistake

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy [hunk 8]
```diff
@@ -60,17 +60,19 @@ class J2objcPlugin implements Plugin<Project> {
...
+                if (arcTranslateArg && !arcCompilerArg || !arcTranslateArg && arcCompilerArg) {
+                    logger.warn "${evaluatedProject.name}: using ARC with J2ObjC, the project is missing one of the two flags required:\n" +
```
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy]: Should this be logger.error since we know it's going to fail? My concern is that this warning gets berried behind an avalanche of other errors and someone misses the useful advice.

**Comment by brunobowden** [comment]
LGTM - merging in now

**Comment by brunobowden** [comment]
One last thing - please squash the commits

**Comment by confile** [comment]
@brunobowden It is still only one commit.

**Comment by brunobowden** [comment]
Might have just needed a browser refresh on my end. In any case, merging now...
