### PR TITLE
Windows Unit Tests All Fixed (fix #402)

### LINKED ISSUE #402: Fix 37 failing unit-tests on Windows
https://ci.appveyor.com/project/madvayApiAccess/j2objc-gradle/build/1.0.1.master-78rcmxiq

fyi @gocursor

```
[00:01:22] gradlew.bat build
[00:01:28] :buildStamp
[00:01:28] 
[00:01:28] :compileJava
[00:01:29] 
[00:01:29] :compileGroovy
[00:01:29]  
[00:01:29] UP-TO-DATE
[00:01:29] :processResources
[00:01:29]  
[00:01:29] UP-TO-DATE
[00:01:29] :classes
[00:01:29] :jar
[00:01:29] 
[00:01:29] :groovydoc
[00:01:36] 
[00:01:36] :publishPluginGroovyDocsJar
[00:01:36] 
[00:01:36] :publishPluginJar
[00:01:36] 
[00:01:36] :javadoc
[00:01:38] 
[00:01:38] :publishPluginJavaDocsJar
[00:01:38] 
[00:01:38] :assemble
[00:01:38] 
[00:01:38] :compileTestJava
[00:01:38]  
[00:01:38] UP-TO-DATE
[00:01:38] 
[00:01:38] :compileTestGroovy
[00:01:42] 
[00:01:42] :processTestResources
[00:01:42] 
[00:01:42] :testClasses
[00:01:42] 
[00:01:42] :test
[00:01:45] 
[00:01:45] 
[00:01:45] com.github.j2objccontrib.j2objcgradle.J2objcConfigTest > testGetDestDirFile_AllVariations 
[00:01:45] FAILED
[00:01:45] 
[00:01:45]     Assertion failed: 
[00:01:45] 
[00:01:45]     assert pDir + '/build/j2objcOutputs/lib' == ext.getDestLibDirFile().absolutePath
[00:01:45]            |                                    |   |                   |
[00:01:45]            |                                    |   |                   C:\Users\appveyor\AppData\Local\Temp\1\gradle1922822926706482096projectDir\build\j2objcOutputs\lib
[00:01:45]            |                                    |   C:\Users\appveyor\AppData\Local\Temp\1\gradle1922822926706482096projectDir\build\j2objcOutputs\lib
[00:01:45]            |                                    com.github.j2objccontrib.j2objcgradle.J2objcConfig@6cc46b6b
[00:01:45]            C:\Users\appveyor\AppData\Local\Temp\1\gradle1922822926706482096projectDir
[00:01:45]         at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:398)
[00:01:45]         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:648)
[00:01:45]         at com.github.j2objccontrib.j2objcgradle.J2objcConfigTest.testGetDestDirFile_AllVariations(J2objcConfigTest.groovy:65)
[00:01:47] 
[00:01:47] com.github.j2objccontrib.j2objcgradle.J2objcConfigTest > testConstructor FAILED
[00:01:47]     Assertion failed: 
[00:01:47] 
[00:01:47]     assert ext.destSrcMainDir == projectDir + '/build/j2objcOutputs/src/main'
[00:01:47]            |   |                 |
[00:01:47]            |   |                 C:\Users\appveyor\AppData\Local\Temp\1\gradle6441424807897521003projectDir
[00:01:47]            |   C:\Users\appveyor\AppData\Local\Temp\1\gradle6441424807897521003projectDir\build/j2objcOutputs/src/main
[00:01:47]            com.github.j2objccontrib.j2objcgradle.J2objcConfig@567ee063
[00:01:47]         at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:398)
[00:01:47]         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:648)
[00:01:47]         at com.github.j2objccontrib.j2objcgradle.J2objcConfigTest.testConstructor(J2objcConfigTest.groovy:54)
[00:01:50] 
[00:01:50] com.github.j2objccontrib.j2objcgradle.MultiProjectTest > twoProjectsWithDependsOnJ2objcLib_Works FAILED
[00:01:50]     org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':testProject8'.
[00:01:50]         at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:79)
[00:01:50]         at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:74)
[00:01:50]         at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
[00:01:50]         at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:487)
[00:01:50]         at org.gradle.api.internal.project.AbstractProject.evaluationDependsOn(AbstractProject.java:555)
[00:01:50]         at org.gradle.api.internal.project.AbstractProject.evaluationDependsOn(AbstractProject.java:547)
[00:01:50]         at com.github.j2objccontrib.j2objcgradle.J2objcConfig.dependsOnJ2objcLib(J2objcConfig.groovy:318)
[00:01:50]         at com.github.j2objccontrib.j2objcgradle.J2objcConfig$dependsOnJ2objcLib.call(Unknown Source)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:50]         at com.github.j2objccontrib.j2objcgradle.MultiProjectTest.twoProjectsWithDependsOnJ2objcLib_Works(MultiProjectTest.groovy:57)
[00:01:50] 
[00:01:50]         Caused by:
[00:01:50]         org.gradle.api.InvalidUserDataException: Cannot convert URL 'C:UsersappveyorAppDataLocalTemp1J2OBJC_HOME4224230331391642566' to a file.
[00:01:50]             at org.gradle.api.internal.file.AbstractFileResolver.convertObjectToFile(AbstractFileResolver.java:190)
[00:01:50]             at org.gradle.api.internal.file.BaseDirFileResolver.doResolve(BaseDirFileResolver.java:69)
[00:01:50]             at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:80)
[00:01:50]             at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:62)
[00:01:50]             at org.gradle.api.internal.file.DefaultFileOperations.file(DefaultFileOperations.java:72)
[00:01:50]             at org.gradle.api.internal.project.AbstractProject.file(AbstractProject.java:615)
[00:01:50]             at com.github.j2objccontrib.j2objcgradle.tasks.Utils.j2objcHome(Utils.groovy:189)
[00:01:50]             at com.github.j2objccontrib.j2objcgradle.tasks.Utils$j2objcHome$0.call(Unknown Source)
[00:01:50]             at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:50]             at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:50]             at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:50]             at com.github.j2objccontrib.j2objcgradle.J2objcPlugin$_apply_closure1_closure3.doCall(J2objcPlugin.groovy:67)
[00:01:50]             at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:50]             at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:50]             at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:50]             at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:50]             at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
[00:01:50]             at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
[00:01:50]             at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
[00:01:50]             at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
[00:01:50]             at groovy.lang.Closure.call(Closure.java:423)
[00:01:50]             at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
[00:01:50]             at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
[00:01:50]             at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:87)
[00:01:50]             at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
[00:01:50]             at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
[00:01:50]             at com.sun.proxy.$Proxy18.afterEvaluate(Unknown Source)
[00:01:50]             at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
[00:01:50]             ... 10 more
[00:01:50] 
[00:01:50] com.github.j2objccontrib.j2objcgradle.tasks.AssembleLibrariesTaskTest > testAssembleLibraries FAILED
[00:01:50]     Assertion failed: 
[00:01:50] 
[00:01:50]     assert ((String) expectedSpec.destDir).equals((String) copySpec.destDir)
[00:01:50]                      |            |        |               |        |
[00:01:50]                      |            |        false           |        C:\Users\appveyor\AppData\Local\Temp\1\gradle7553222077368502482projectDir\build\j2objcOutputs\lib
[00:01:50]                      |            |                        org.gradle.api.internal.file.copy.DefaultCopySpec@72161768
[00:01:50]                      |            C:\Users\appveyor\AppData\Local\Temp\1\gradle7553222077368502482projectDir/build/j2objcOutputs/lib
[00:01:50]                      org.gradle.api.internal.file.copy.DefaultCopySpec@85ae75c
[00:01:50]         at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:398)
[00:01:50]         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:648)
[00:01:50]         at com.github.j2objccontrib.j2objcgradle
[00:01:50] .tasks.MockProjectExec$_demandCopyAndReturn_closure3.doCall(MockProjectExec.groovy:160)
[00:01:50]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:50]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:50]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:50]         at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:50]         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
[00:01:50]         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
[00:01:50]         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
[00:01:50]         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(Abstract
[00:01:50] CallSite.java:108)
[00:01:50]         at groovy.mock.interceptor.MockInterceptor.beforeInvoke(MockInterceptor.groovy:33)
[00:01:50]         at groovy.mock.interceptor.MockProxyMetaClass.invokeMethod(MockProxyMetaClass.java:78)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:50]         at com.github.j2objccontrib.j2objcgradle.tasks.MockProjectExec$_closure1.doCall(MockProjectExec.groovy:70)
[00:01:50]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:50]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:50]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:50]         at java.lang.reflect.Method.invoke(Meth
[00:01:50] od.java:606)
[00:01:50]         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
[00:01:50]         at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:80)
[00:01:50]         at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1114)
[00:01:50]         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:50]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.projectCopy(Utils.groovy:427)
[00:01:50]         at com.github.j2objccontrib.j2objcgradle.tasks.AssembleLibrariesTask.assembleLibraries(AssembleLibrariesTask.groovy:57)
[00:01:50]         at com.github.j2objccontrib.j2objcgradle.ta
[00:01:50] sks.AssembleLibrariesTask$assembleLibraries.call(Unknown Source)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
[00:01:50]         at com.github.j2objccontrib.j2objcgradle.tasks.AssembleLibrariesTaskTest.testAssembleLibraries(AssembleLibrariesTaskTest.groovy:60)
[00:01:50] 
[00:01:50] com.github.j2objccontrib.j2objcgradle.tasks.AssembleResourcesTaskTest > testAssembleResources_Basic FAILED
[00:01:50]     Assertion failed: 
[00:01:50] 
[00:01:50]     assert expectedPathsList.equals(pathsList)
[00:01:50]            |                 |      |
[00:01:50]            |                 false  [C:\Users\appveyor\AppData\Local\Temp\1\gradle7615822383935723681projectDir\build\j2objcOutputs\src\main\resources]
[00:01:50]            [C:\Users\appveyor\AppData\Local\Temp\1\gradle7615822383935723681projectDir/build/j2objcOutputs/src/main/resources]
[00:01:50]         at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:398)
[00:01:50]         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:648)
[00:01:50]         at com.github.j2objccontrib.j2objcgradle.tasks.MockProjectExec$_demandDeleteAndReturn_closure4.doCall(MockProjectExec.groovy:205)
[00:01:50]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:50]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:50]         at sun.reflect.
[00:01:50] DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:50]         at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:50]         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
[00:01:50]         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
[00:01:50]         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
[00:01:50]         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
[00:01:50]         at groovy.mock.interceptor.MockInterceptor.beforeInvoke(MockInterceptor.groovy:33)
[00:01:50]         at groovy.mock.interceptor.MockProxyMetaClass.invokeMethod(MockProxyMetaClass.java:78)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite
[00:01:50] .call(PogoMetaClassSite.java:39)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:50]         at com.github.j2objccontrib.j2objcgradle.tasks.MockProjectExec$_closure1.doCall(MockProjectExec.groovy:72)
[00:01:50]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:50]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:50]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:50]         at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:50]         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
[00:01:50]         at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:80)
[00:01:50]         at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.ja
[00:01:50] va:1114)
[00:01:50]         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:50]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.projectDelete(Utils.groovy:443)
[00:01:50]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.syncResourcesTo(Utils.groovy:400)
[00:01:50]         at com.github.j2objccontrib.j2objcgradle.tasks.AssembleResourcesTask.assembleResources(AssembleResourcesTask.groovy:56)
[00:01:50]         at com.github.j2objccontrib.j2objcgradle.tasks.AssembleResourcesTask$assembleResources.call(Unknown Source)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:50]         at 
[00:01:50] org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:50]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
[00:01:50]         at com.github.j2objccontrib.j2objcgradle.tasks.AssembleResourcesTaskTest.testAssembleResources_Basic(AssembleResourcesTaskTest.groovy:67)
[00:01:51] 
[00:01:51] com.github.j2objccontrib.j2objcgradle.tasks.AssembleSourceTaskTest > testAssembleSource FAILED
[00:01:51]     Assertion failed: 
[00:01:51] 
[00:01:51]     assert expectedPathsList.equals(pathsList)
[00:01:51]            |                 |      |
[00:01:51]            |                 false  [C:\Users\appveyor\AppData\Local\Temp\1\gradle1961344721188826486projectDir\build\j2objcOutputs\src\main\objc]
[00:01:51]            [C:\Users\appveyor\AppData\Local\Temp\1\gradle1961344721188826486projectDir/build/j2objcOutputs/src/main/objc]
[00:01:51]         at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:398)
[00:01:51]         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:648)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.MockProjectExec$_demandDeleteAndReturn_closure4.doCall(MockProjectExec.groovy:205)
[00:01:51]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:51]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:51]         at sun.reflect.DelegatingMethodAccess
[00:01:51] orImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:51]         at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:51]         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
[00:01:51]         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
[00:01:51]         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
[00:01:51]         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:51]         at groovy.mock.interceptor.MockInterceptor.beforeInvoke(MockInterceptor.groovy:33)
[00:01:51]         at groovy.mock.interceptor.MockProxyMetaClass.invokeMethod(MockProxyMetaClass.java:78)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSit
[00:01:51] e.java:54)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.MockProjectExec$_closure1.doCall(MockProjectExec.groovy:72)
[00:01:51]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:51]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:51]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:51]         at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:51]         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
[00:01:51]         at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:80)
[00:01:51]         at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1114)
[00:01:51]         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.projectDelete(Utils.groovy:443)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.AssembleSourceTask.clearDestSrcDirWithChecks(AssembleSourceTask.groovy:79)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.AssembleSourceTask.assembleSource(AssembleSourceTask.groovy:52)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.AssembleSourceTask$assembleSource.call(Unknown Source)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.AssembleSourceTaskTest.testAssembleSource(AssembleSourceTaskTest.groovy:69)
[00:01:51] 
[00:01:51] com.github.j2objccontrib.j2objcgradle.tasks.CycleFinderTaskTest > cycleFinder_Advanced_NoFiles_Success 
[00:01:51] FAILED
[00:01:51] 
[00:01:51]     org.gradle.api.InvalidUserDataException: Cannot convert URL 'C:UsersappveyorAppDataLocalTemp1J2OBJC_HOME6730993242305372154' to a file.
[00:01:51]         at org.gradle.api.internal.file.AbstractFileResolver.convertObjectToFile(AbstractFileResolver.java:190)
[00:01:51]         at org.gradle.api.internal.file.BaseDirFileResolver.doResolve(BaseDirFileResolver.java:69)
[00:01:51]         at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:80)
[00:01:51]         at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:62)
[00:01:51]         at org.gradle.api.internal.file.DefaultFileOperations.file(DefaultFileOperations.java:72)
[00:01:51]         at org.gradle.api.internal.project.AbstractProject.file(AbstractProject.java:615)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.j2objcHome(Utils.groovy:189)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.CycleFinderTask.getJ2objcHome(CycleFinderTask.groovy:68)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.CycleFinderTask_Decorated.getJ2objcHome(Unknown Source)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.CycleFinderTask.cycleFinder(CycleFinderTask.groovy:96)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.CycleFinderTask$cycleFinder.call(Unknown Source)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.CycleFinderTaskTest.cycleFinder_Advanced_NoFiles_Success(CycleFinderTaskTest.groovy:159)
[00:01:51] 
[00:01:51] com.github.j2objccontrib.j2objcgradle.tasks.CycleFinderTaskTest > cycleFinder_Windows 
[00:01:51] FAILED
[00:01:51] 
[00:01:51]     org.gradle.api.InvalidUserDataException: Cannot convert URL 'C:UsersappveyorAppDataLocalTemp1J2OBJC_HOME1106856454429076868' to a file.
[00:01:51]         at org.gradle.api.internal.file.AbstractFileResolver.convertObjectToFile(AbstractFileResolver.java:190)
[00:01:51]         at org.gradle.api.internal.file.BaseDirFileResolver.doResolve(BaseDirFileResolver.java:69)
[00:01:51]         at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:80)
[00:01:51]         at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:62)
[00:01:51]         at org.gradle.api.internal.file.DefaultFileOperations.file(DefaultFileOperations.java:72)
[00:01:51]         at org.gradle.api.internal.project.AbstractProject.file(AbstractProject.java:615)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.j2objcHome(Utils.groovy:189)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.CycleFinderTask.getJ2objcHome(CycleFinderTask.groovy:68)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.CycleFinderTask_Decorated.getJ2objcHome(Unknown Source)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.CycleFinderTask.cycleFinder(CycleFinderTask.groovy:96)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.CycleFinderTask$cycleFinder.call(Unknown Source)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.CycleFinderTaskTest.cycleFinder_Windows(CycleFinderTaskTest.groovy:99)
[00:01:51] 
[00:01:51] com.github.j2objccontrib.j2objcgradle.tasks.CycleFinderTaskTest > cycleFinder_Simple_NoFiles_Success FAILED
[00:01:51]     org.gradle.api.InvalidUserDataException: Cannot convert URL 'C:UsersappveyorAppDataLocalTemp1J2OBJC_HOME6832072978408186807' to a file.
[00:01:51]         at org.gradle.api.internal.file.AbstractFileResolver.convertObjectToFile(AbstractFileResolver.java:190)
[00:01:51]         at org.gradle.api.internal.file.BaseDirFileResolver.doResolve(BaseDirFileResolver.java:69)
[00:01:51]         at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:80)
[00:01:51]         at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:62)
[00:01:51]         at org.gradle.api.internal.file.DefaultFileOperations.file(DefaultFileOperations.java:72)
[00:01:51]         at org.gradle.api.internal.project.AbstractProject.file(AbstractProject.java:615)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.j2objcHome(Utils.groovy:189)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.CycleFinderTask.getJ2ob
[00:01:51] jcHome(CycleFinderTask.groovy:68)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.CycleFinderTask_Decorated.getJ2objcHome(Unknown Source)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.CycleFinderTask.cycleFinder(CycleFinderTask.groovy:96)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.CycleFinderTask$cycleFinder.call(Unknown Source)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.CycleFinderTaskTest.cycleFinder_Simple_NoFiles_Success(CycleFinderTaskTest.groovy:69)
[00:01:51] 
[00:01:51] com.github.j2objccontrib.j2objcgradle.tasks.CycleFinderTaskTest > cycleFinder_Advanced_NoFiles_Failure 
[00:01:51] FAILED
[00:01:51] 
[00:01:51]     java.lang.Exception: Unexpected exception, expected<org.gradle.api.InvalidUserDataException> but was<junit.framework.AssertionFailedError>
[00:01:51] 
[00:01:51]         Caused by:
[00:01:51]         junit.framework.AssertionFailedError: verify[0]: expected 1..1 call(s) to 'exec' but was called 0 time(s).
[00:01:51]             at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[00:01:51]             at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
[00:01:51]             at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[00:01:51]             at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
[00:01:51]             at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
[00:01:51]             at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:71)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:81)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
[00:01:51]             at groovy.mock.interceptor.Demand.verify(Demand.groovy:51)
[00:01:51]             at groovy.mock.interceptor.Demand$verify.call(Unknown Source)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:51]             at groovy.mock.interceptor.StrictExpectation.verify(StrictExpectation.groovy:78)
[00:01:51]             at groovy.mock.interceptor.StrictExpectation$verify$0.call(Unknown Source)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
[00:01:51]             at groovy.mock.interceptor.MockFor.verify(MockFor.groovy:150)
[00:01:51]             at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:51]             at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:51]             at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:51]             at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:166)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:51]             at com.github.j2objccontrib.j2objcgradle.tasks.MockProjectExec.verify(MockProjectExec.groovy:131)
[00:01:51]             at com.github.j2objccontrib.j2objcgradle.tasks.MockProjectExec$verify$1.call(Unknown Source)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
[00:01:51]             at com.github.j2objccontrib.j2objcgradle.tasks.CycleFinderTaskTest.cycleFinder_Advanced_NoFiles_Failure(CycleFinderTaskTest.groovy:193)
[00:01:51] 
[00:01:51] com.github.j2objccontrib.j2objcgradle.tasks.CycleFinderTaskTest > cycleFinder_Simple_NoFiles_Failure 
[00:01:51] FAILED
[00:01:51] 
[00:01:51]     java.lang.Exception: Unexpected exception, expected<org.gradle.api.InvalidUserDataException> but was<junit.framework.AssertionFailedError>
[00:01:51] 
[00:01:51]         Caused by:
[00:01:51]         junit.framework.AssertionFailedError: verify[0]: expected 1..1 call(s) to 'exec' but was called 0 time(s).
[00:01:51]             at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[00:01:51]             at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
[00:01:51]             at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[00:01:51]             at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
[00:01:51]             at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
[00:01:51]             at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:71)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:81)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
[00:01:51]             at groovy.mock.interceptor.Demand.verify(Demand.groovy:51)
[00:01:51]             at groovy.mock.interceptor.Demand$verify.call(Unknown Source)
[00:01:51]             at groovy.mock.interceptor.StrictExpectation.verify(StrictExpectation.groovy:78)
[00:01:51]             at groovy.mock.interceptor.StrictExpectation$verify$0.call(Unknown Source)
[00:01:51]             at groovy.mock.interceptor.MockFor.verify(MockFor.groovy:150)
[00:01:51]             at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:51]             at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:51]             at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:51]             at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:166)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:51]             at com.github.j2objccontrib.j2objcgradle.tasks.MockProjectExec.verify(MockProjectExec.groovy:131)
[00:01:51]             at com.github.j2objccontrib.j2objcgradle.tasks.MockProjectExec$verify$1.call(Unknown Source)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:51]             at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
[00:01:51]             at com.github.j2objccontrib.j2objcgradle.tasks.CycleFinderTaskTest.cycleFinder_Simple_NoFiles_Failure(CycleFinderTaskTest.groovy:129)
[00:01:51] 
[00:01:51] com.github.j2objccontrib.j2objcgradle.tasks.PackLibrariesTaskTest > testPackLibraries 
[00:01:51] FAILED
[00:01:51] 
[00:01:51]     Assertion failed: 
[00:01:51] 
[00:01:51]     assert expectedPathsList.equals(pathsList)
[00:01:51]            |                 |      |
[00:01:51]            |                 false  [C:\Users\appveyor\AppData\Local\Temp\1\gradle1446375644877778434projectDir\build\packedBinaries\testProject18-j2objcStaticLibrary\iosDebug]
[00:01:51]            [C:\Users\appveyor\AppData\Local\Temp\1\gradle1446375644877778434projectDir/build/packedBinaries/testProject18-j2objcStaticLibrary/iosDebug]
[00:01:51]         at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:398)
[00:01:51]         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:648)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.MockProjectExec$_demandDeleteAndReturn_closure4.doCall(MockProjectExec.groovy:205)
[00:01:51]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:51]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:51]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:51]         at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:51]         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
[00:01:51]         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
[00:01:51]         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
[00:01:51]         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:51]         at groovy.mock.interceptor.MockInterceptor.beforeInvoke(MockInterceptor.groovy:33)
[00:01:51]         at groovy.mock.interceptor.MockProxyMetaClass.invokeMethod(MockProxyMetaClass.java:78)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.MockProjectExec$_closure1.doCall(MockProjectExec.groovy:72)
[00:01:51]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:51]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:51]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:51]         at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:51]         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
[00:01:51]         at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:80)
[00:01:51]         at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1114)
[00:01:51]         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.projectDelete(Utils.groovy:443)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.PackLibrariesTask.packLibraries(PackLibrariesTask.groovy:63)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.PackLibrariesTask$packLibraries.call(Unknown Source)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:51]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
[00:01:51]         at com.github.j2objccontrib.j2objcgradle.tasks.PackLibrariesTaskTest.testPackLibraries(PackLibrariesTaskTest.groovy:91)
[00:01:52] 
[00:01:52] com.github.j2objccontrib.j2objcgradle.tasks.TestTaskTest > testTaskAction_OneTest 
[00:01:52] FAILED
[00:01:52] 
[00:01:52]     Assertion failed: 
[00:01:52] 
[00:01:52]     assert expectedPathsList.equals(pathsList)
[00:01:52]            |                 |      |
[00:01:52]            |                 false  [C:\Users\appveyor\AppData\Local\Temp\1\gradle8384058488588206514projectDir\build\j2objcTest\debug]
[00:01:52]            [C:\Users\appveyor\AppData\Local\Temp\1\gradle8384058488588206514projectDir/build/j2objcTest/debug]
[00:01:52]         at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:398)
[00:01:52]         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:648)
[00:01:52]         at com.github.j2objccontrib.j2objcgradle.tasks.MockProjectExec$_demandDeleteAndReturn_closure4.doCall(MockProjectExec.groovy:205)
[00:01:52]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:52]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:52]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:52]         at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:52]         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
[00:01:52]         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
[00:01:52]         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
[00:01:52]         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
[00:01:52]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:52]         at groovy.mock.interceptor.MockInterceptor.beforeInvoke(MockInterceptor.groovy:33)
[00:01:52]         at groovy.mock.interceptor.MockProxyMetaClass.invokeMethod(MockProxyMetaClass.java:78)
[00:01:52]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:52]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:52]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
[00:01:52]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:52]         at com.github.j2objccontrib.j2objcgradle.tasks.MockProjectExec$_closure1.doCall(MockProjectExec.groovy:72)
[00:01:52]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:52]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:52]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:52]         at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:52]         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
[00:01:52]         at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:80)
[00:01:52]         at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1114)
[00:01:52]         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
[00:01:52]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:52]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:52]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
[00:01:52]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:52]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.projectDelete(Utils.groovy:443)
[00:01:52]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.syncResourcesTo(Utils.groovy:400)
[00:01:52]         at com.github.j2objccontrib.j2objcgradle.tasks.TestTask.test(TestTask.groovy:105)
[00:01:52]         at com.github.j2objccontrib.j2objcgradle.tasks.TestTask$test.call(Unknown Source)
[00:01:52]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:52]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:52]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
[00:01:52]         at com.github.j2objccontrib.j2objcgradle.tasks.TestTaskTest.testTaskAction_OneTest(TestTaskTest.groovy:188)
[00:01:52] 
[00:01:52] com.github.j2objccontrib.j2objcgradle.tasks.TestTaskTest > testGetTestNames_Simple 
[00:01:52] FAILED
[00:01:52] 
[00:01:52]     Assertion failed: 
[00:01:52] 
[00:01:52]     assert expectedTestNames == testNames
[00:01:52]            |                 |  |
[00:01:52]            |                 |  [src\test\java\com\example\parent\ParentClass, src\test\java\com\example\parent\subdir\SubdirClass, src\test\java\com\example\other\OtherClass]
[00:01:52]            |                 false
[00:01:52]            [com.example.parent.ParentClass, com.example.parent.subdir.SubdirClass, com.example.other.OtherClass]
[00:01:52]         at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:398)
[00:01:52]         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:648)
[00:01:52]         at com.github.j2objccontrib.j2objcgradle.tasks.TestTaskTest.testGetTestNames_Simple(TestTaskTest.groovy:66)
[00:01:52] 
[00:01:52] com.github.j2objccontrib.j2objcgradle.tasks.TestTaskTest > testTaskAction_MultipleTests 
[00:01:52] FAILED
[00:01:52] 
[00:01:52]     Assertion failed: 
[00:01:52] 
[00:01:52]     assert expectedPathsList.equals(pathsList)
[00:01:52]            |                 |      |
[00:01:52]            |                 false  [C:\Users\appveyor\AppData\Local\Temp\1\gradle4202615742116329874projectDir\build\j2objcTest\debug]
[00:01:52]            [C:\Users\appveyor\AppData\Local\Temp\1\gradle4202615742116329874projectDir/build/j2objcTest/debug]
[00:01:52]         at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:398)
[00:01:52]         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:648)
[00:01:52]         at com.github.j2objccontrib.j2objcgradle.tasks.MockProjectExec$_demandDeleteAndReturn_closure4.doCall(MockProjectExec.groovy:205)
[00:01:52]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:52]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:52]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:52]         at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:52]         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
[00:01:52]         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
[00:01:52]         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
[00:01:52]         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
[00:01:52]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:52]         at groovy.mock.interceptor.MockInterceptor.beforeInvoke(MockInterceptor.groovy:33)
[00:01:52]         at groovy.mock.interceptor.MockProxyMetaClass.invokeMethod(MockProxyMetaClass.java:78)
[00:01:52]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:52]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:52]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
[00:01:52]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:52]         at com.github.j2objccontrib.j2objcgradle.tasks.MockProjectExec$_closure1.doCall(MockProjectExec.groovy:72)
[00:01:52]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:52]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:52]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:52]         at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:52]         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
[00:01:52]         at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:80)
[00:01:52]         at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1114)
[00:01:52]         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
[00:01:52]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:52]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:52]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
[00:01:52]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:52]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.projectDelete(Utils.groovy:443)
[00:01:52]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.syncResourcesTo(Utils.groovy:400)
[00:01:52]         at com.github.j2objccontrib.j2objcgradle.tasks.TestTask.test(TestTask.groovy:105)
[00:01:52]         at com.github.j2objccontrib.j2objcgradle.tasks.TestTask$test.call(Unknown Source)
[00:01:52]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:52]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:52]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
[00:01:52]         at com.github.j2objccontrib.j2objcgradle.tasks.TestTaskTest.testTaskAction_MultipleTests(TestTaskTest.groovy:209)
[00:01:52] 
[00:01:52] com.github.j2objccontrib.j2objcgradle.tasks.TestTaskTest > testTaskAction_ZeroTestUnexpected FAILED
[00:01:52]     java.lang.AssertionError: 
[00:01:52]     Expected: (an instance of org.gradle.api.InvalidUserDataException and exception with message a string containing "Unit tests are strongly encouraged with J2ObjC" and exception with message a string containing "testMinExpectedTests 0")
[00:01:52]          but: an instance of org.gradle.api.InvalidUserDataException <Assertion failed: 
[00:01:52] 
[00:01:52]     assert expectedPathsList.equals(pathsList)
[00:01:52]            |                 |      |
[00:01:52]            |                 false  [C:\Users\appveyor\AppData\Local\Temp\1\gradle2513378344265554905projectDir\build\j2objcTest\debug]
[00:01:52]            [C:\Users\appveyor\AppData\Local\Temp\1\gradle2513378344265554905projectDir/build/j2objcTest/debug]
[00:01:52]     > is a org.codehaus.groovy.runtime.powerassert.PowerAssertionError
[00:01:52]     Stacktrace was: Assertion failed: 
[00:01:52] 
[00:01:52]     assert expectedPathsList.equals(pathsList)
[00:01:52]            |                 |      |
[00:01:52]            |          
[00:01:52]        false  [C:\Users\appveyor\AppData\Local\Temp\1\gradle2513378344265554905projectDir\build\j2objcTest\debug]
[00:01:52]            [C:\Users\appveyor\AppData\Local\Temp\1\gradle2513378344265554905projectDir/build/j2objcTest/debug]
[00:01:52] 
[00:01:52]     	at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:398)
[00:01:52]     	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:648)
[00:01:52]     	at com.github.j2objccontrib.j2objcgradle.tasks.MockProjectExec$_demandDeleteAndReturn_closure4.doCall(MockProjectExec.groovy:205)
[00:01:52]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:52]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:52]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:52]     	at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:52]     	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
[00:01:52]     	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
[00:01:52]     	at 
[00:01:52] org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
[00:01:52]     	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
[00:01:52]     	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:52]     	at groovy.mock.interceptor.MockInterceptor.beforeInvoke(MockInterceptor.groovy:33)
[00:01:52]     	at groovy.mock.interceptor.MockProxyMetaClass.invokeMethod(MockProxyMetaClass.java:78)
[00:01:52]     	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:52]     	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:52]     	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
[00:01:52]     	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:52]     	at com.github.j2objccontrib.j2objcgradle.tasks.MockProjectExec$_closure1.doCall(MockProjectExec.groovy:72)
[00:01:52]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:52]     	at sun.r
[00:01:52] eflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:52]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:52]     	at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:52]     	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
[00:01:52]     	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:80)
[00:01:52]     	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1114)
[00:01:52]     	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
[00:01:52]     	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:52]     	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:52]     	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
[00:01:52]     	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:52]     	at com.github.j2objccontrib.j2objcgradle.tasks.Utils.projectDelete(Utils.groo
[00:01:52] vy:443)
[00:01:52]     	at com.github.j2objccontrib.j2objcgradle.tasks.Utils.syncResourcesTo(Utils.groovy:400)
[00:01:52]     	at com.github.j2objccontrib.j2objcgradle.tasks.TestTask.test(TestTask.groovy:105)
[00:01:52]     	at com.github.j2objccontrib.j2objcgradle.tasks.TestTask$test.call(Unknown Source)
[00:01:52]     	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:52]     	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:52]     	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
[00:01:52]     	at com.github.j2objccontrib.j2objcgradle.tasks.TestTaskTest.testTaskAction_ZeroTestUnexpected(TestTaskTest.groovy:146)
[00:01:52]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:52]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:52]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:52]     	at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:52]     	at org.junit.runners.m
[00:01:52] odel.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[00:01:52]     	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[00:01:52]     	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[00:01:52]     	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[00:01:52]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[00:01:52]     	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
[00:01:52]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[00:01:52]     	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[00:01:52]     	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[00:01:52]     	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[00:01:52]     	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[00:01:52]     	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[00:01:52]     	at org.junit.runners.Paren
[00:01:52] tRunner.runChildren(ParentRunner.java:288)
[00:01:52]     	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[00:01:52]     	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[00:01:52]     	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[00:01:52]     	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
[00:01:52]     	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
[00:01:52]     	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
[00:01:52]     	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
[00:01:52]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:52]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:52]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:52]     	at java.lang.reflect.Meth
[00:01:52] od.invoke(Method.java:606)
[00:01:52]     	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
[00:01:52]     	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[00:01:52]     	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
[00:01:52]     	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
[00:01:52]     	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
[00:01:52]     	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
[00:01:52]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:52]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:52]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:52]     	at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:52]     	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
[00:01:52] 
[00:01:52]     	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[00:01:52]     	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
[00:01:52]     	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
[00:01:52]     	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
[00:01:52]     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[00:01:52]     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[00:01:52]     	at java.lang.Thread.run(Thread.java:745)
[00:01:52] 
[00:01:52] com.github.j2objccontrib.j2objcgradle.tasks.TestTaskTest > testTaskAction_CantParseOutput FAILED
[00:01:52]     java.lang.Exception: Unexpected exception, expected<org.gradle.api.InvalidUserDataException> but was<org.codehaus.groovy.runtime.powerassert.PowerAssertionError>
[00:01:52] 
[00:01:52]         Caused by:
[00:01:52]         Assertion failed: 
[00:01:52] 
[00:01:52]         assert expectedPathsList.equals(pathsList)
[00:01:52]                |                 |      |
[00:01:52]                |                 false  [C:\Users\appveyor\AppData\Local\Temp\1\gradle2071453896520589765projectDir\build\j2objcTest\debug]
[00:01:52]                [C:\Users\appveyor\AppData\Local\Temp\1\gradle2071453896520589765projectDir/build/j2objcTest/debug]
[00:01:52]             at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:398)
[00:01:52]             at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:648)
[00:01:52]             at com.github.j2objccontrib.j2objcgradle.tasks.MockProjectExec$_demandDeleteAndReturn_closure4.doCall(MockProjectExec.groovy:205)
[00:01:52]       
[00:01:52]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:52]             at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:52]             at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:52]             at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:52]             at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
[00:01:52]             at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
[00:01:52]             at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
[00:01:52]             at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
[00:01:52]             at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:52]             at groovy.mock.interceptor.MockInterceptor.beforeInvoke(MockInterceptor.groovy:33)
[00:01:52]             at groovy.mock.interceptor.MockProxyMetaClass.invokeMethod(MockProxyMetaClass.java:78)
[00:01:52]             at org.codehaus.groovy.runt
[00:01:52] ime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:52]             at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:52]             at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
[00:01:52]             at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:52]             at com.github.j2objccontrib.j2objcgradle.tasks.MockProjectExec$_closure1.doCall(MockProjectExec.groovy:72)
[00:01:52]             at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:52]             at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:52]             at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:52]             at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:52]             at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
[00:01:52]             at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:80)
[00:01:52]  
[00:01:52]            at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1114)
[00:01:52]             at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
[00:01:52]             at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:52]             at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:52]             at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
[00:01:52]             at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:52]             at com.github.j2objccontrib.j2objcgradle.tasks.Utils.projectDelete(Utils.groovy:443)
[00:01:52]             at com.github.j2objccontrib.j2objcgradle.tasks.Utils.syncResourcesTo(Utils.groovy:400)
[00:01:52]             at com.github.j2objccontrib.j2objcgradle.tasks.TestTask.test(TestTask.groovy:105)
[00:01:52]             at com.github.j2objccontrib.j2objcgradle.tasks.TestTask$test.call(Unknown Source)
[00:01:52]             at org.codehaus.groovy.runtime.callsite.CallSiteA
[00:01:52] rray.defaultCall(CallSiteArray.java:45)
[00:01:52]             at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:52]             at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
[00:01:52]             at com.github.j2objccontrib.j2objcgradle.tasks.TestTaskTest.testTaskAction_CantParseOutput(TestTaskTest.groovy:230)
[00:01:53] 
[00:01:53] com.github.j2objccontrib.j2objcgradle.tasks.TestTaskTest > testGetTestNames_PackagePrefixes 
[00:01:53] FAILED
[00:01:53] 
[00:01:53]     Assertion failed: 
[00:01:53] 
[00:01:53]     assert expectedTestNames == testNames
[00:01:53]            |                 |  |
[00:01:53]            |                 |  [src\test\java\com\example\parent\ParentOneClass, src\test\java\com\example\parent\ParentTwoClass, src\test\java\com\example\parent\subdir\SubdirClass, src\test\java\com\example\other\OtherClass, src\test\java\com\example\noprefix\NoPrefixClass]
[00:01:53]            |                 false
[00:01:53]            [PrntPrefixParentOneClass, PrntPrefixParentTwoClass, SubPrefixSubdirClass, OthPrefixOtherClass, com.example.noprefix.NoPrefixClass]
[00:01:53]         at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:398)
[00:01:53]         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:648)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.TestTaskTest.testGetTestNames_PackagePrefixes(TestTaskTest.groovy:95)
[00:01:53] 
[00:01:53] com.github.j2objccontrib.j2objcgradle.tasks.TestTaskTest > testTaskAction_ZeroTestExpected 
[00:01:53] FAILED
[00:01:53] 
[00:01:53]     Assertion failed: 
[00:01:53] 
[00:01:53]     assert expectedPathsList.equals(pathsList)
[00:01:53]            |                 |      |
[00:01:53]            |                 false  [C:\Users\appveyor\AppData\Local\Temp\1\gradle6101703838322112203projectDir\build\j2objcTest\debug]
[00:01:53]            [C:\Users\appveyor\AppData\Local\Temp\1\gradle6101703838322112203projectDir/build/j2objcTest/debug]
[00:01:53]         at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:398)
[00:01:53]         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:648)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.MockProjectExec$_demandDeleteAndReturn_closure4.doCall(MockProjectExec.groovy:205)
[00:01:53]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:53]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:53]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:53]         at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:53]         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
[00:01:53]         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
[00:01:53]         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
[00:01:53]         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
[00:01:53]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:53]         at groovy.mock.interceptor.MockInterceptor.beforeInvoke(MockInterceptor.groovy:33)
[00:01:53]         at groovy.mock.interceptor.MockProxyMetaClass.invokeMethod(MockProxyMetaClass.java:78)
[00:01:53]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:53]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:53]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
[00:01:53]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.MockProjectExec$_closure1.doCall(MockProjectExec.groovy:72)
[00:01:53]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:53]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:53]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:53]         at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:53]         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
[00:01:53]         at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:80)
[00:01:53]         at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1114)
[00:01:53]         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
[00:01:53]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:53]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:53]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
[00:01:53]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.projectDelete(Utils.groovy:443)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.syncResourcesTo(Utils.groovy:400)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.TestTask.test(TestTask.groovy:105)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.TestTask$test.call(Unknown Source)
[00:01:53]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:53]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:53]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.TestTaskTest.testTaskAction_ZeroTestExpected(TestTaskTest.groovy:167)
[00:01:53] 
[00:01:53] com.github.j2objccontrib.j2objcgradle.tasks.TranslateTaskTest > translate_J2objcConfig 
[00:01:53] FAILED
[00:01:53] 
[00:01:53]     org.gradle.api.InvalidUserDataException: Cannot convert URL 'C:UsersappveyorAppDataLocalTemp1J2OBJC_HOME3008195626072142263' to a file.
[00:01:53]         at org.gradle.api.internal.file.AbstractFileResolver.convertObjectToFile(AbstractFileResolver.java:190)
[00:01:53]         at org.gradle.api.internal.file.BaseDirFileResolver.doResolve(BaseDirFileResolver.java:69)
[00:01:53]         at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:80)
[00:01:53]         at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:62)
[00:01:53]         at org.gradle.api.internal.file.DefaultFileOperations.file(DefaultFileOperations.java:72)
[00:01:53]         at org.gradle.api.internal.project.AbstractProject.file(AbstractProject.java:615)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.j2objcHome(Utils.groovy:189)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.TranslateTask.getJ2objcHome(TranslateTask.groovy:85)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.TranslateTask_Decorated.getJ2objcHome(Unknown Source)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.TranslateTask.translate(TranslateTask.groovy:215)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.TranslateTask$translate.call(Unknown Source)
[00:01:53]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:53]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:53]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.TranslateTaskTest.translate_J2objcConfig(TranslateTaskTest.groovy:115)
[00:01:53] 
[00:01:53] com.github.j2objccontrib.j2objcgradle.tasks.TranslateTaskTest > translate_Windows FAILED
[00:01:53]     org.gradle.api.InvalidUserDataException: Cannot convert URL 'C:UsersappveyorAppDataLocalTemp1J2OBJC_HOME5518226246406721774' to a file.
[00:01:53]         at org.gradle.api.internal.file.AbstractFileResolver.convertObjectToFile(AbstractFileResolver.java:190)
[00:01:53]         at org.gradle.api.internal.file.BaseDirFileResolver.doResolve(BaseDirFileResolver.java:69)
[00:01:53]         at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:80)
[00:01:53]         at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:62)
[00:01:53]         at org.gradle.api.internal.file.DefaultFileOperations.file(DefaultFileOperations.java:72)
[00:01:53]         at org.gradle.api.internal.project.AbstractProject.file(AbstractProject.java:615)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.j2objcHome(Utils.groovy:189)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.TranslateTask.getJ2objcHome(TranslateTask.gr
[00:01:53] oovy:85)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.TranslateTask_Decorated.getJ2objcHome(Unknown Source)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.TranslateTask.translate(TranslateTask.groovy:215)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.TranslateTask$translate.call(Unknown Source)
[00:01:53]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:53]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:53]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.TranslateTaskTest.translate_Windows(TranslateTaskTest.groovy:84)
[00:01:53] 
[00:01:53] com.github.j2objccontrib.j2objcgradle.tasks.TranslateTaskTest > translate_BasicArguments 
[00:01:53] FAILED
[00:01:53] 
[00:01:53]     org.gradle.api.InvalidUserDataException: Cannot convert URL 'C:UsersappveyorAppDataLocalTemp1J2OBJC_HOME4732979728823164804' to a file.
[00:01:53]         at org.gradle.api.internal.file.AbstractFileResolver.convertObjectToFile(AbstractFileResolver.java:190)
[00:01:53]         at org.gradle.api.internal.file.BaseDirFileResolver.doResolve(BaseDirFileResolver.java:69)
[00:01:53]         at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:80)
[00:01:53]         at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:62)
[00:01:53]         at org.gradle.api.internal.file.DefaultFileOperations.file(DefaultFileOperations.java:72)
[00:01:53]         at org.gradle.api.internal.project.AbstractProject.file(AbstractProject.java:615)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.j2objcHome(Utils.groovy:189)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.TranslateTask.getJ2objcHome(TranslateTask.groovy:85)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.TranslateTask_Decorated.getJ2objcHome(Unknown Source)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.TranslateTask.translate(TranslateTask.groovy:215)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.TranslateTask$translate.call(Unknown Source)
[00:01:53]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:53]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:53]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.TranslateTaskTest.translate_BasicArguments(TranslateTaskTest.groovy:61)
[00:01:53] 
[00:01:53] com.github.j2objccontrib.j2objcgradle.tasks.UtilsTest > testJ2objcHome_LocalPropertiesWithTrailingSlash 
[00:01:53] FAILED
[00:01:53] 
[00:01:53]     org.gradle.api.InvalidUserDataException: Cannot convert URL 'C:UsersappveyorAppDataLocalTemp1J2OBJC_HOME9138243964711388225/' to a file.
[00:01:53]         at org.gradle.api.internal.file.AbstractFileResolver.convertObjectToFile(AbstractFileResolver.java:190)
[00:01:53]         at org.gradle.api.internal.file.BaseDirFileResolver.doResolve(BaseDirFileResolver.java:69)
[00:01:53]         at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:80)
[00:01:53]         at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:62)
[00:01:53]         at org.gradle.api.internal.file.DefaultFileOperations.file(DefaultFileOperations.java:72)
[00:01:53]         at org.gradle.api.internal.project.AbstractProject.file(AbstractProject.java:615)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.j2objcHome(Utils.groovy:189)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.UtilsTest.testJ2objcHome_LocalPropertiesWithTrailingSlash(UtilsTest.groovy:202)
[00:01:53] 
[00:01:53] com.github.j2objccontrib.j2objcgradle.tasks.UtilsTest > testProjectExecLog FAILED
[00:01:53]     java.lang.UnsupportedOperationException: Cannot convert relative path /WORKING_DIR to an absolute file.
[00:01:53]         at org.gradle.api.internal.file.IdentityFileResolver.doResolve(IdentityFileResolver.java:40)
[00:01:53]         at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:80)
[00:01:53]         at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:62)
[00:01:53]         at org.gradle.api.internal.file.AbstractFileResolver$2.create(AbstractFileResolver.java:161)
[00:01:53]         at org.gradle.api.internal.file.AbstractFileResolver$2.create(AbstractFileResolver.java:159)
[00:01:53]         at org.gradle.process.internal.DefaultProcessForkOptions.getWorkingDir(DefaultProcessForkOptions.java:56)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.projectExecLog(Utils.groovy:368)
[00:01:53]         at com.github.j2objccontrib.j2objcgradle.tasks.UtilsTest.testProjectExecLog(UtilsTest.groovy:365)
[00:01:54] 
[00:01:54] com.github.j2objccontrib.j2objcgradle.tasks.UtilsTest > testJ2objcHome_LocalProperties FAILED
[00:01:54]     org.gradle.api.InvalidUserDataException: Cannot convert URL 'C:UsersappveyorAppDataLocalTemp1J2OBJC_HOME556587581629753731' to a file.
[00:01:54]         at org.gradle.api.internal.file.AbstractFileResolver.convertObjectToFile(AbstractFileResolver.java:190)
[00:01:54]         at org.gradle.api.internal.file.BaseDirFileResolver.doResolve(BaseDirFileResolver.java:69)
[00:01:54]         at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:80)
[00:01:54]         at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:62)
[00:01:54]         at org.gradle.api.internal.file.DefaultFileOperations.file(DefaultFileOperations.java:72)
[00:01:54]         at org.gradle.api.internal.project.AbstractProject.file(AbstractProject.java:615)
[00:01:54]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.j2objcHome(Utils.groovy:189)
[00:01:54]         at com.github.j2objccontrib.j2objcgradle.tasks.UtilsTest.testJ2objcHome_LocalProperties
[00:01:54] (UtilsTest.groovy:190)
[00:01:54] 
[00:01:54] com.github.j2objccontrib.j2objcgradle.tasks.UtilsTest > testProjectDeleteCopyCallSequence 
[00:01:54] FAILED
[00:01:54] 
[00:01:54]     java.lang.UnsupportedOperationException: Cannot convert relative path /INIT_WORKING_DIR to an absolute file.
[00:01:54]         at org.gradle.api.internal.file.IdentityFileResolver.doResolve(IdentityFileResolver.java:40)
[00:01:54]         at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:80)
[00:01:54]         at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:62)
[00:01:54]         at org.gradle.api.internal.file.AbstractFileResolver$2.create(AbstractFileResolver.java:161)
[00:01:54]         at org.gradle.api.internal.file.AbstractFileResolver$2.create(AbstractFileResolver.java:159)
[00:01:54]         at org.gradle.process.internal.DefaultProcessForkOptions.getWorkingDir(DefaultProcessForkOptions.java:56)
[00:01:54]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.projectExecLog(Utils.groovy:368)
[00:01:54]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils$projectExecLog$1.callStatic(Unknown Source)
[00:01:54]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
[00:01:54]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:157)
[00:01:54]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.projectExec(Utils.groovy:521)
[00:01:54]         at com.github.j2objccontrib.j2objcgradle.tasks.UtilsTest.testProjectDeleteCopyCallSequence(UtilsTest.groovy:625)
[00:01:54] 
[00:01:54] com.github.j2objccontrib.j2objcgradle.tasks.UtilsTest > testJoinedPathArg 
[00:01:54] FAILED
[00:01:54] 
[00:01:54]     Assertion failed: 
[00:01:54] 
[00:01:54]     assert expected == joinedPathArg
[00:01:54]            |           |
[00:01:54]            |           C:\Users\appveyor\AppData\Local\Temp\1\gradle5544622063136287005projectDir\relative_file1;C:\Users\appveyor\AppData\Local\Temp\1\gradle5544622063136287005projectDir\relative_file2;C:\Users\appveyor\AppData\Local\Temp\1\gradle5544622063136287005projectDir\absoluteFile
[00:01:54]            C;\Users\appveyor\AppData\Local\Temp\1\gradle5544622063136287005projectDir/relative_file1;C;\Users\appveyor\AppData\Local\Temp\1\gradle5544622063136287005projectDir/relative_file2;/absoluteFile
[00:01:54]         at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:398)
[00:01:54]         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:648)
[00:01:54]         at com.github.j2objccontrib.j2objcgradle.tasks.UtilsTest.testJoinedPathArg(UtilsTest.groovy:303)
[00:01:54] 
[00:01:54] com.github.j2objccontrib.j2objcgradle.tasks.UtilsTest > testProjectExec_StdErr FAILED
[00:01:54]     org.gradle.api.InvalidUserDataException: Command Line Failed:
[00:01:54]     echo echo-stdout
[00:01:54]     Working Dir:
[00:01:54]     C:\Users\appveyor\AppData\Local\Temp\1\gradle6581057022934850598projectDir
[00:01:54]     Cause:
[00:01:54]     org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'echo''
[00:01:54]     Standard Output:
[00:01:54] 
[00:01:54]     Error Output:
[00:01:54]     fake-stderr
[00:01:54]         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[00:01:54]         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
[00:01:54]         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[00:01:54]         at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
[00:01:54]         at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
[00:01:54]         at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstr
[00:01:54] uctor(ConstructorSite.java:102)
[00:01:54]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
[00:01:54]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
[00:01:54]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:194)
[00:01:54]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.projectExec(Utils.groovy:522)
[00:01:54]         at com.github.j2objccontrib.j2objcgradle.tasks.UtilsTest.testProjectExec_StdErr(UtilsTest.groovy:495)
[00:01:54] 
[00:01:54]         Caused by:
[00:01:54]         org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'echo''
[00:01:54] 
[00:01:54]             Caused by:
[00:01:54]             net.rubygrapefruit.platform.NativeException: Could not start 'echo'
[00:01:54] 
[00:01:54]                 Caused by:
[00:01:54]                 java.io.IOException: Cannot run program "echo" (in directory "C:\Users\appveyor\AppData\Local\Temp\1\gradle6581057022934850598projectDir"): CreateProcess error=2, The system cannot 
[00:01:54] find the file specified
[00:01:54] 
[00:01:54]                     Caused by:
[00:01:54]                     java.io.IOException: CreateProcess error=2, The system cannot find the file specified
[00:01:54] 
[00:01:54] com.github.j2objccontrib.j2objcgradle.tasks.UtilsTest > testProjectExec_StdOut FAILED
[00:01:54]     org.gradle.api.InvalidUserDataException: Command Line Failed:
[00:01:54]     echo written-stdout
[00:01:54]     Working Dir:
[00:01:54]     C:\Users\appveyor\AppData\Local\Temp\1\gradle6465736007759937515projectDir
[00:01:54]     Cause:
[00:01:54]     org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'echo''
[00:01:54]     Standard Output:
[00:01:54] 
[00:01:54]     Error Output:
[00:01:54]         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[00:01:54]         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
[00:01:54]         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[00:01:54]         at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
[00:01:54]         at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
[00:01:54]         at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(Construc
[00:01:54] torSite.java:102)
[00:01:54]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:194)
[00:01:54]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.projectExec(Utils.groovy:522)
[00:01:54]         at com.github.j2objccontrib.j2objcgradle.tasks.UtilsTest.testProjectExec_StdOut(UtilsTest.groovy:474)
[00:01:54] 
[00:01:54]         Caused by:
[00:01:54]         org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'echo''
[00:01:54] 
[00:01:54]             Caused by:
[00:01:54]             net.rubygrapefruit.platform.NativeException: Could not start 'echo'
[00:01:54] 
[00:01:54]                 Caused by:
[00:01:54]                 java.io.IOException: Cannot run program "echo" (in directory "C:\Users\appveyor\AppData\Local\Temp\1\gradle6465736007759937515projectDir"): CreateProcess error=2, The system cannot find the file specified
[00:01:54] 
[00:01:54]                     Caused by:
[00:01:54]                     java.io.IOException: CreateProcess error=2, The system cannot find the file specified
[00:01:55] 
[00:01:55] com.github.j2objccontrib.j2objcgradle.tasks.UtilsTest > testProjectExec_MatchRegexFailed 
[00:01:55] FAILED
[00:01:55] 
[00:01:55]     Assertion failed: 
[00:01:55] 
[00:01:55]     assert exception.toString().equals(expected)
[00:01:55]            |         |          |      |
[00:01:55]            |         |          false  org.gradle.api.InvalidUserDataException: Command Line Succeeded:
[00:01:55]            |         |                 echo echo-stdout
[00:01:55]            |         |                 Working Dir:
[00:01:55]            |         |                 C:\Users\appveyor\AppData\Local\Temp\1\gradle7448445194020058028projectDir
[00:01:55]            |         |                 Cause:
[00:01:55]            |         |                 org.gradle.api.InvalidUserDataException: Unable to find expected expected output in stdout or stderr
[00:01:55]            |         |                 Failed Regex Match: /(no\/match\n)/
[00:01:55]            |         |                 Standard Output:
[00:01:55]            |         |                 echo-stdout
[00:01:55]            |         |                  
[00:01:55]            |         |                 Error Output:
[00:01:55]            |         org.gradle.api.InvalidUserDataException: Command Line Failed:
[00:01:55]            |         echo echo-stdout
[00:01:55]            |         Working Dir:
[00:01:55]            |         C:\Users\appveyor\AppData\Local\Temp\1\gradle7448445194020058028projectDir
[00:01:55]            |         Cause:
[00:01:55]            |         org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'echo''
[00:01:55]            |         Standard Output:
[00:01:55]            |          
[00:01:55]            |         Error Output:
[00:01:55]            org.gradle.api.InvalidUserDataException: Command Line Failed:
[00:01:55]            echo echo-stdout
[00:01:55]            Working Dir:
[00:01:55]            C:\Users\appveyor\AppData\Local\Temp\1\gradle7448445194020058028projectDir
[00:01:55]            Cause:
[00:01:55]            org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'echo''
[00:01:55]            Standard Output:
[00:01:55]         
[00:01:55]            Error Output:
[00:01:55]         at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:398)
[00:01:55]         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:648)
[00:01:55]         at com.github.j2objccontrib.j2objcgradle.tasks.UtilsTest.testProjectExec_MatchRegexFailed(UtilsTest.groovy:572)
[00:01:55] 
[00:01:55] com.github.j2objccontrib.j2objcgradle.tasks.UtilsTest > testSyncResourcesTo 
[00:01:55] FAILED
[00:01:55] 
[00:01:55]     Assertion failed: 
[00:01:55] 
[00:01:55]     assert expectedPathsList.equals(pathsList)
[00:01:55]            |                 |      |
[00:01:55]            |                 false  [C:\Users\appveyor\AppData\Local\Temp\1\gradle7949846233937627404projectDir\SYNC_DIR]
[00:01:55]            [C:\Users\appveyor\AppData\Local\Temp\1\gradle7949846233937627404projectDir/SYNC_DIR]
[00:01:55]         at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:398)
[00:01:55]         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:648)
[00:01:55]         at com.github.j2objccontrib.j2objcgradle.tasks.MockProjectExec$_demandDeleteAndReturn_closure4.doCall(MockProjectExec.groovy:205)
[00:01:55]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:55]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:55]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:55]         at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:55]         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
[00:01:55]         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
[00:01:55]         at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
[00:01:55]         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
[00:01:55]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:55]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:55]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
[00:01:55]         at groovy.mock.interceptor.MockInterceptor.beforeInvoke(MockInterceptor.groovy:33)
[00:01:55]         at groovy.mock.interceptor.MockProxyMetaClass.invokeMethod(MockProxyMetaClass.java:78)
[00:01:55]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:55]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:55]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
[00:01:55]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:55]         at com.github.j2objccontrib.j2objcgradle.tasks.MockProjectExec$_closure1.doCall(MockProjectExec.groovy:72)
[00:01:55]         at sun.reflect.GeneratedMethodAccessor129.invoke(Unknown Source)
[00:01:55]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:55]         at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:55]         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
[00:01:55]         at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:80)
[00:01:55]         at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1114)
[00:01:55]         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
[00:01:55]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
[00:01:55]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:55]         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
[00:01:55]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[00:01:55]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.projectDelete(Utils.groovy:443)
[00:01:55]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.syncResourcesTo(Utils.groovy:400)
[00:01:55]         at com.github.j2objccontrib.j2objcgradle.tasks.UtilsTest.testSyncResourcesTo(UtilsTest.groovy:408)
[00:01:56] 
[00:01:56] com.github.j2objccontrib.j2objcgradle.tasks.UtilsTest > testSrcSet_GetSrcDirs 
[00:01:56] FAILED
[00:01:56] 
[00:01:56]     Assertion failed: 
[00:01:56] 
[00:01:56]     assert Arrays.equals(expected, srcDirsPaths)
[00:01:56]                   |      |         |
[00:01:56]                   false  |         [C:\Users\appveyor\AppData\Local\Temp\1\gradle6723435272626611315projectDir\src\main\java]
[00:01:56]                          [C:\Users\appveyor\AppData\Local\Temp\1\gradle6723435272626611315projectDir/src/main/java]
[00:01:56]         at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:398)
[00:01:56]         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:648)
[00:01:56]         at com.github.j2objccontrib.j2objcgradle.tasks.UtilsTest.testSrcSet_GetSrcDirs(UtilsTest.groovy:229)
[00:01:56] 
[00:01:56] com.github.j2objccontrib.j2objcgradle.tasks.UtilsTest > testGetLocalProperty_LocalPropertiesInvalidKey FAILED
[00:01:56]     java.lang.AssertionError: 
[00:01:56]     Expected: (an instance of org.gradle.api.InvalidUserDataException and exception with message a string containing "Invalid J2ObjC Gradle Plugin property: j2objc.written-invalid-key" and exception with message a string containing "From local.properties: C:\Users\appveyor\AppData\Local\Temp\1\gradle7590660295879866281projectDir/local.properties" and exception with message a string containing "debug.enabled")
[00:01:56]          but: exception with message a string containing "From local.properties: C:\Users\appveyor\AppData\Local\Temp\1\gradle7590660295879866281projectDir/local.properties" message was "Invalid J2ObjC Gradle Plugin property: j2objc.written-invalid-key
[00:01:56]     From local.properties: C:\Users\appveyor\AppData\Local\Temp\1\gradle7590660295879866281projectDir\local.properties
[00:01:56]     Valid Keys: [debug.enabled, enabledArchs, home, release.enabled, translateOnlyMode]"
[00:01:56]    
[00:01:56]  Stacktrace was: org.gradle.api.InvalidUserDataException: Invalid J2ObjC Gradle Plugin property: j2objc.written-invalid-key
[00:01:56]     From local.properties: C:\Users\appveyor\AppData\Local\Temp\1\gradle7590660295879866281projectDir\local.properties
[00:01:56]     Valid Keys: [debug.enabled, enabledArchs, home, release.enabled, translateOnlyMode]
[00:01:56]     	at com.github.j2objccontrib.j2objcgradle.tasks.Utils$_getLocalProperty_closure2.doCall(Utils.groovy:155)
[00:01:56]     	at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
[00:01:56]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:56]     	at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:56]     	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
[00:01:56]     	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
[00:01:56]     	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
[00:01:56]     	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
[00:01:56]     	at groovy.lang.Closure.c
[00:01:56] all(Closure.java:423)
[00:01:56]     	at groovy.lang.Closure.call(Closure.java:439)
[00:01:56]     	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1379)
[00:01:56]     	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1310)
[00:01:56]     	at com.github.j2objccontrib.j2objcgradle.tasks.Utils.getLocalProperty(Utils.groovy:148)
[00:01:56]     	at com.github.j2objccontrib.j2objcgradle.tasks.Utils.getLocalProperty(Utils.groovy)
[00:01:56]     	at com.github.j2objccontrib.j2objcgradle.tasks.UtilsTest.testGetLocalProperty_LocalPropertiesInvalidKey(UtilsTest.groovy:180)
[00:01:56]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:56]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:56]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:56]     	at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:56]     	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[00:01:56]     	at org.junit.internal.runners.model
[00:01:56] .ReflectiveCallable.run(ReflectiveCallable.java:12)
[00:01:56]     	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[00:01:56]     	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[00:01:56]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[00:01:56]     	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
[00:01:56]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[00:01:56]     	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[00:01:56]     	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[00:01:56]     	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[00:01:56]     	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[00:01:56]     	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[00:01:56]     	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[00:01:56]     	at org.junit.runners.ParentRunner.access$000(ParentRunner.
[00:01:56] java:58)
[00:01:56]     	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[00:01:56]     	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[00:01:56]     	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
[00:01:56]     	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
[00:01:56]     	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
[00:01:56]     	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
[00:01:56]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:56]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:56]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:56]     	at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:56]     	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDis
[00:01:56] patch.java:35)
[00:01:56]     	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[00:01:56]     	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
[00:01:56]     	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
[00:01:56]     	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
[00:01:56]     	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
[00:01:56]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:56]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:01:56]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:01:56]     	at java.lang.reflect.Method.invoke(Method.java:606)
[00:01:56]     	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
[00:01:56]     	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[00:01:56]     	at or
[00:01:56] g.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
[00:01:56]     	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
[00:01:56]     	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
[00:01:56]     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[00:01:56]     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[00:01:56]     	at java.lang.Thread.run(Thread.java:745)
[00:01:56] 
[00:01:56] com.github.j2objccontrib.j2objcgradle.tasks.UtilsTest > testProjectExec_ThrowException 
[00:01:56] FAILED
[00:01:56] 
[00:01:56]     java.lang.UnsupportedOperationException: Cannot convert relative path /INIT_WORKING_DIR to an absolute file.
[00:01:56]         at org.gradle.api.internal.file.IdentityFileResolver.doResolve(IdentityFileResolver.java:40)
[00:01:56]         at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:80)
[00:01:56]         at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:62)
[00:01:56]         at org.gradle.api.internal.file.AbstractFileResolver$2.create(AbstractFileResolver.java:161)
[00:01:56]         at org.gradle.api.internal.file.AbstractFileResolver$2.create(AbstractFileResolver.java:159)
[00:01:56]         at org.gradle.process.internal.DefaultProcessForkOptions.getWorkingDir(DefaultProcessForkOptions.java:56)
[00:01:56]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.projectExecLog(Utils.groovy:368)
[00:01:56]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils$projectExecLog$1.callStatic(Unknown Source)
[00:01:56]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
[00:01:56]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils$projectExecLog$1.callStatic(Unknown Source)
[00:01:56]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.projectExec(Utils.groovy:521)
[00:01:56]         at com.github.j2objccontrib.j2objcgradle.tasks.UtilsTest.testProjectExec_ThrowException(UtilsTest.groovy:593)
[00:01:56] 
[00:01:56] com.github.j2objccontrib.j2objcgradle.tasks.XcodeTaskTest > getPodFile_Valid 
[00:01:56] FAILED
[00:01:56] 
[00:01:56]     Assertion failed: 
[00:01:56] 
[00:01:56]     assert expectedPath == podFile.absolutePath
[00:01:56]            |            |  |       |
[00:01:56]            |            |  |       C:\Users\appveyor\AppData\Local\Temp\1\ios\Podfile
[00:01:56]            |            |  C:\Users\appveyor\AppData\Local\Temp\1\ios\Podfile
[00:01:56]            |            false
[00:01:56]            C:\Users\appveyor\AppData\Local\Temp\1\ios/Podfile
[00:01:56]         at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:398)
[00:01:56]         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:648)
[00:01:56]         at com.github.j2objccontrib.j2objcgradle.tasks.XcodeTaskTest.getPodFile_Valid(XcodeTaskTest.groovy:59)
[00:01:57] 
[00:01:57] com.github.j2objccontrib.j2objcgradle.tasks.XcodeTaskTest > testXcodeConfig_NeedsPodInit 
[00:01:57] FAILED
[00:01:57] 
[00:01:57]     Assertion failed: 
[00:01:57] 
[00:01:57]     assert exception.toString().contains('The Podfile must be created with this command')
[00:01:57]            |         |          |
[00:01:57]            |         |          false
[00:01:57]            |         org.gradle.api.InvalidUserDataException: Cannot convert URL 'C:UsersappveyorAppDataLocalTemp1J2OBJC_HOME2962654637868308440' to a file.
[00:01:57]            org.gradle.api.InvalidUserDataException: Cannot convert URL 'C:UsersappveyorAppDataLocalTemp1J2OBJC_HOME2962654637868308440' to a file.
[00:01:57]         at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:398)
[00:01:57]         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:648)
[00:01:57]         at com.github.j2objccontrib.j2objcgradle.tasks.XcodeTaskTest.testXcodeConfig_NeedsPodInit(XcodeTaskTest.groovy:222)
[00:01:57] 
[00:01:57] com.github.j2objccontrib.j2objcgradle.tasks.XcodeTaskTest > testXcodeConfig_Basic 
[00:01:57] FAILED
[00:01:57] 
[00:01:57]     org.gradle.api.InvalidUserDataException: Cannot convert URL 'C:UsersappveyorAppDataLocalTemp1J2OBJC_HOME2267534996985931802' to a file.
[00:01:57]         at org.gradle.api.internal.file.AbstractFileResolver.convertObjectToFile(AbstractFileResolver.java:190)
[00:01:57]         at org.gradle.api.internal.file.BaseDirFileResolver.doResolve(BaseDirFileResolver.java:69)
[00:01:57]         at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:80)
[00:01:57]         at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:62)
[00:01:57]         at org.gradle.api.internal.file.DefaultFileOperations.file(DefaultFileOperations.java:72)
[00:01:57]         at org.gradle.api.internal.project.AbstractProject.file(AbstractProject.java:615)
[00:01:57]         at com.github.j2objccontrib.j2objcgradle.tasks.Utils.j2objcHome(Utils.groovy:189)
[00:01:57]         at com.github.j2objccontrib.j2objcgradle.tasks.XcodeTask.getJ2objcHome(XcodeTask.groovy:57)
[00:01:57]         at com.github.j2objccontrib.j2objcgradle.tasks.XcodeTask_Decorated.getJ2objcHome(Unknown Source)
[00:01:57]         at com.github.j2objccontrib.j2objcgradle.tasks.XcodeTask.xcodeConfig(XcodeTask.groovy:111)
[00:01:57]         at com.github.j2objccontrib.j2objcgradle.tasks.XcodeTask$xcodeConfig$2.call(Unknown Source)
[00:01:57]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
[00:01:57]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
[00:01:57]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
[00:01:57]         at com.github.j2objccontrib.j2objcgradle.tasks.XcodeTaskTest.testXcodeConfig_Basic(XcodeTaskTest.groovy:136)
[00:01:58] 
[00:01:58] 106 tests completed, 37 failed
[00:01:58] 
[00:01:58] :test 
[00:01:58] FAILED
[00:01:58] 
[00:01:58] 
[00:01:58] FAILURE: 
[00:01:58] Build failed with an exception.
[00:01:58] 
[00:01:58] 
[00:01:58] * What went wrong:
[00:01:58] Execution failed for task ':test'.
[00:01:58] > 
[00:01:58] There were failing tests. See the report at: file:///C:/projects/j2objc-gradle/build/reports/tests/index.html
[00:01:58] 
[00:01:58] * Try:
[00:01:58] Run with 
[00:01:58] --stacktrace
[00:01:58]  option to get the stack trace. Run with 
[00:01:58] --info
[00:01:58]  or 
[00:01:58] --debug
[00:01:58]  option to get more log output.
[00:01:58] 
[00:01:58] BUILD FAILED
[00:01:58] 
[00:01:58] 
[00:01:58] Total time: 36.391 secs
[00:01:59] Command exited with code 1
```

### LINKED ISSUE #422: echo command fails on Windows (testProjectExec unit tests)
The `echo` command is used in a number of unit tests, particularly the testProjectExec unit tests in UtilsTest.groovy. This command isn't supported on Windows. The tests are currently disabled on Windows but should be enabled once an alternative is established to the `echo` command. Current exception:

org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'echo''

### PR DESCRIPTION
**Pull request by brunobowden**
Major:
- Fix #402 - Windows 37 unit tests failures
- Fix #422 - echo command fails on Windows
- Disabled only failing test on Windows: #374

Minor:
- Fake OS specific file and path separators
- Explicit setFakeOS methods, e.g. setFakeOSWindows()
- Default to using native OS rather than fake OS for most unit tests
- Small number of unit tests use fakeOSName
- ‘inTestMustFakeOS’ setting removed

### CODE REVIEW

**Comment by brunobowden** [comment]
@advayDev1 - ignore for now, still in progress

**Comment by brunobowden** [comment]
@advayDev1 and @gocursor - I've gone through and fixed up all the unit tests on Windows. A small number (~4) were disabled with TODOs. This was complicated by not having a Windows machine ;-). @cursor, if you could look at trying to fix some of the disabled Windows tasks marked with TODOs, that would be helpful, in particular it needs a substitute for running 'echo' on the command line.

@advayDev1 - I still have one weird failure locally but it doesn't happen on the build bots. Very happy to see this all working:

screen shot 2015-08-25 at 4 00 15 pm

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/Utils.groovy [hunk 1]
```diff
@@ -99,6 +135,29 @@ class Utils {
         }
     }
 
+    // Same as File.separator but can mocked using fakeOSName
```
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/Utils.groovy]: s/mocked/faked/ below as well

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/Utils.groovy [hunk 2]
```diff
@@ -99,6 +135,29 @@ class Utils {
...
+    // Same as File.pathSeparator but can mocked using fakeOSName
+    static String pathSeparator() {
+        if (isWindows()) {
+            return ';'
+        } else {
+            return ':'
+        }
+    }
+
+    static String osTestCompatPath(String path) {
```
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/Utils.groovy]: i'm not understanding the name of this method

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/Utils.groovy [hunk 3]
```diff
@@ -60,37 +60,73 @@ class Utils {
...
+        return osName.contains('windows')
+    }
+
+    static boolean isWindowsNoFake() {
+        String osName = getLowerCaseOSName(true)
+        return osName.contains('windows')
+    }
+
+    @VisibleForTesting
+    static final String windowsAbsolutePathPrefix = 'C:'
```
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/Utils.groovy]: Paths can start with any VOLUME:\ I believe on Windows.
People may well have multiple drives and be working on D:

File: build.gradle [hunk 4]
```diff
@@ -48,7 +48,6 @@ test {
         // of just pointing to an HTML file.
         exceptionFormat = 'full'
     }
-    systemProperty 'inTestMustFakeOS', 'true'
```
Comment (advayDev1) [inline build.gradle]: Remind me why it is ok to remove this.
Are we no longer testing the same functionality on all OS-es (in the unit tests), up to path separators?

File: src/test/groovy/com/github/j2objccontrib/j2objcgradle/MultiProjectTest.groovy [hunk 5]
```diff
@@ -49,6 +49,12 @@ class MultiProjectTest {
 
     @Test
     void twoProjectsWithDependsOnJ2objcLib_Works() {
+        // TODO: can this test run on Windows? Current error:
```
Comment (advayDev1) [inline src/test/groovy/com/github/j2objccontrib/j2objcgradle/MultiProjectTest.groovy]: The problem is that Window is using JDK 8 and this is #374 
Please add the issue number here.

File: src/test/groovy/com/github/j2objccontrib/j2objcgradle/tasks/UtilsTest.groovy [hunk 6]
```diff
@@ -464,6 +553,11 @@ class UtilsTest {
 
     @Test
     void testProjectExec_StdOut() {
+        // TODO: figure out equivalent of 'echo' command on Windows
```
Comment (advayDev1) [inline src/test/groovy/com/github/j2objccontrib/j2objcgradle/tasks/UtilsTest.groovy]: Can you file an issue for this, and reference it here and the 2 below?

**Comment by advayDev1** [comment]
Awesome - really nice work!

Can you add to CONTRIBUTING.md style guide the canonical way to construct a file paths such that they work across platforms and across fakes OSes?  I see sometimes you using new File(parent, child).absolutePath and sometime concating with the Utils separator.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/Utils.groovy (hunk 1 above)
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/Utils.groovy]: done

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/Utils.groovy (hunk 2 above)
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/Utils.groovy]: Removed method

File: build.gradle (hunk 4 above)
Comment (brunobowden) [inline build.gradle]: It's very hard to completely mock the OS.... including for example classes like java.io.File. I think a better approach is to use the fully native calls for as many of the unit tests as possible. Indeed, that's how someone will use the plugin. With passing builds on multiple OSs, we automatically get good coverage.

There are a small number of cases where you'd like to prevent breaking another OS. So for the tasks that only run on OS X, it uses setFakeOSMacOSX() and runs those tests. For most tasks it's better to get the coverage on the different systems.

File: src/test/groovy/com/github/j2objccontrib/j2objcgradle/MultiProjectTest.groovy (hunk 5 above)
Comment (brunobowden) [inline src/test/groovy/com/github/j2objccontrib/j2objcgradle/MultiProjectTest.groovy]: Added link

File: src/test/groovy/com/github/j2objccontrib/j2objcgradle/tasks/UtilsTest.groovy (hunk 6 above)
Comment (brunobowden) [inline src/test/groovy/com/github/j2objccontrib/j2objcgradle/tasks/UtilsTest.groovy]: Added reference to the 3 disabled tests:
https://github.com/j2objc-contrib/j2objc-gradle/issues/422

File: build.gradle (hunk 4 above)
Comment (advayDev1) [inline build.gradle]: that's fair.  now that we have hermetic Linux + Win + OSX builds gating the merge, I'm less worried about this.

**Comment by brunobowden** [comment]
@advayDev1 - PTAL, this is all fixed up, including the local failure that @gocursor also saw. It should be ready for a LGTM now.

File: src/test/groovy/com/github/j2objccontrib/j2objcgradle/tasks/UtilsTest.groovy [hunk 7]
```diff
@@ -545,11 +672,19 @@ class UtilsTest {
         ByteArrayOutputStream stdout = new ByteArrayOutputStream()
         ByteArrayOutputStream stderr = new ByteArrayOutputStream()
 
+        // TODO: Windows alternative to 'echo' command
+        // https://github.com/j2objc-contrib/j2objc-gradle/issues/422
+        String executableCmd = 'echo'
+        if (Utils.isWindowsNoFake()) {
+            // executableCmd = '????'
```
Comment (advayDev1) [inline src/test/groovy/com/github/j2objccontrib/j2objcgradle/tasks/UtilsTest.groovy]: looks like your new echo solution is needed here too?

**Comment by advayDev1** [comment]
LGTM.  see 1 comment in the code and also please respond to my comment above:
> Can you add to CONTRIBUTING.md style guide the canonical way to construct a file paths such that they work across platforms and across fakes OSes? I see sometimes you using new File(parent, child).absolutePath and sometime concating with the Utils separator.

File: src/test/groovy/com/github/j2objccontrib/j2objcgradle/tasks/UtilsTest.groovy (hunk 7 above)
Comment (brunobowden) [inline src/test/groovy/com/github/j2objccontrib/j2objcgradle/tasks/UtilsTest.groovy]: Good point. Fixed that up too.

**Comment by brunobowden** [comment]
I'll add the section to CONTRIBUTING in my next PR. Just waiting on builds and then I'll merge.

**Comment by advayDev1** [comment]
sg
