### PR TITLE
Fix resource loading for j2objc unit tests

### LINKED ISSUE #309: Resource loading within test executables
Currently the podspec will copy the resources to Xcode using CocoaPods. I want to test out and make sure we support loading of resources within Xcode.

### PR DESCRIPTION
**Pull request by brunobowden**
- Fixes #309
- Fix MockProjectExec so it can handle multiple calls
- MockProjectExec support for project.copy() verification
- Logging of workingDir in projectExec
- j2objcTestContent directory for assembling and running tests
- TestTask now has main/test resources as @InputFiles

TESTED=yes
- Added Project mocking tests:
- testProjectExec_MockProjectExec
- testProjectCopy_MockProjectExec
- testProjectCopy_MockProjectExecTwoCalls

### CODE REVIEW

**Comment by brunobowden** [comment]
@advayDev1, @confile - PTAL. This steps up testing on the plugin another notch, along with fixing loading resources from the j2objc generated unit tests.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy [hunk 1]
```diff
@@ -105,6 +105,8 @@ class J2objcPlugin implements Plugin<Project> {
 
             // Note the '(debug|release)TestJ2objcExecutable' tasks are dynamically created by the Objective-C plugin.
             // It is specified by the testJ2objc native component in NativeCompilation.groovy.
+            // TODO: copy and run debug and release tests within j2objcTestResources at the
+            // TODO: same time instead of destroying and recreating j2objcTestResources twice
```
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy]: just indent the second line's internal text.  double todo is odd

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/TestTask.groovy [hunk 2]
```diff
@@ -70,18 +71,29 @@ class TestTask extends DefaultTask {
...
-
-        String binary = testBinaryFile.path
-        logger.debug("Test Binary: $binary")
-
         // list of test names: ['com.example.dir.ClassOneTest', 'com.example.dir.ClassTwoTest']
         // depends on "--prefixes dir/prefixes.properties" in translateArgs
         Properties packagePrefixes = Utils.packagePrefixes(project, translateArgs)
         List<String> testNames = getTestNames(project, getTestSrcFiles(), packagePrefixes)
 
+        // Test executable must be run from the same directory as the resources
```
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/TestTask.groovy]: shouldn't the construction of the resources be its own task?  then test execution relies on assembly of the binary and assembly of the resources, which is consistent with most other of our own tasks and other plugins

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/TestTask.groovy [hunk 3]
```diff
@@ -70,18 +71,29 @@ class TestTask extends DefaultTask {
...
+        project.delete(getJ2objcTestResourcesDir())
+        Utils.copyResources(project, 'main', getJ2objcTestResourcesDir())
+        Utils.copyResources(project, 'test', getJ2objcTestResourcesDir())
+        Utils.projectCopy(project, {
+            from testBinaryFile
+            into getJ2objcTestResourcesDir()
+        })
+        File copiedTestBinary = new File(getJ2objcTestResourcesDir(), testBinaryFile.getName())
```
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/TestTask.groovy]: if we're putting the binary with the resources, maybe "testContent" would be a better name for the directory.

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/TestTask.groovy [hunk 4]
```diff
@@ -70,18 +71,29 @@ class TestTask extends DefaultTask {
...
-        logger.debug("Test Binary: $binary")
-
         // list of test names: ['com.example.dir.ClassOneTest', 'com.example.dir.ClassTwoTest']
         // depends on "--prefixes dir/prefixes.properties" in translateArgs
         Properties packagePrefixes = Utils.packagePrefixes(project, translateArgs)
         List<String> testNames = getTestNames(project, getTestSrcFiles(), packagePrefixes)
 
+        // Test executable must be run from the same directory as the resources
+        project.delete(getJ2objcTestResourcesDir())
+        Utils.copyResources(project, 'main', getJ2objcTestResourcesDir())
```
Comment (advayDev1) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/TestTask.groovy]: all of the resources need to be added to our input file set, if they aren't already

**Comment by advayDev1** [comment]
comments provided

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy (hunk 1 above)
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPlugin.groovy]: remove double TODO

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/TestTask.groovy (hunk 4 above)
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/TestTask.groovy]: Added as @Input

**Comment by advayDev1** [comment]
per discussion, fix the input file set, and then the split into two tasks can be in a separate PR

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/TestTask.groovy (hunk 3 above)
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/TestTask.groovy]: testResouces => testContent

File: src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/TestTask.groovy (hunk 2 above)
Comment (brunobowden) [inline src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/TestTask.groovy]: Added main/test resources as @InputFiles. I'll do the separate assemble tasks in another commit.

**Comment by advayDev1** [comment]
lgtm, after you squash.  there's an odd SQUASH commit in there right now...

**Comment by brunobowden** [comment]
I thought the separate SQUASH would make it easier for you to view the incremental changes in GitHub but it doesn't help at all.

**Comment by brunobowden** [comment]
Tested against my app and it correctly reran the java and j2objc tests when the main or test resources were changed.
